import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * Export a markdown string to a PDF file
 * @param content The markdown content to export
 * @param filename The name of the file
 */
export const exportToPDF = async (content: string, filename: string) => {
  // Create a temporary div to render the markdown
  const element = document.createElement('div');
  element.style.padding = '40px';
  element.style.width = '800px';
  element.style.backgroundColor = 'white';
  element.style.color = '#1a1a1a';
  element.style.fontFamily = 'Arial, sans-serif';
  element.style.lineHeight = '1.6';
  
  // Basic markdown to HTML conversion for the PDF
  // We'll use a simple approach here, or we could use a library if needed
  // But for a clean PDF, we can just format the text nicely
  const formattedContent = content
    .replace(/^# (.*$)/gm, '<h1 style="color: #5A5A40; border-bottom: 2px solid #5A5A40; padding-bottom: 10px;">$1</h1>')
    .replace(/^## (.*$)/gm, '<h2 style="color: #5A5A40; margin-top: 20px;">$1</h2>')
    .replace(/^### (.*$)/gm, '<h3 style="color: #333; margin-top: 15px;">$1</h3>')
    .replace(/^\* (.*$)/gm, '<li>$1</li>')
    .replace(/^- (.*$)/gm, '<li>$1</li>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>');

  element.innerHTML = `
    <div style="text-align: center; margin-bottom: 30px;">
      <h3 style="color: #5A5A40; margin: 0;">DARE DIGITAL LIBRARY</h3>
      <p style="font-size: 12px; color: #666; margin: 5px 0;">Heritage-Based Curriculum (HBC) Alignment Tools</p>
    </div>
    <div>${formattedContent}</div>
    <div style="margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; font-size: 10px; color: #999; text-align: center;">
      Generated by DARA AI Assistant - DARE Digital Library &copy; ${new Date().getFullYear()}
    </div>
  `;

  document.body.appendChild(element);

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
    });
    
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgProps = pdf.getImageProperties(imgData);
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
    
    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
    pdf.save(`${filename}.pdf`);
  } catch (error) {
    console.error('Error generating PDF:', error);
    alert('Failed to generate PDF. Please try again.');
  } finally {
    document.body.removeChild(element);
  }
};

/**
 * Share content using the Web Share API or fallback to clipboard
 * @param title The title of the shared content
 * @param text The text content to share
 */
export const shareContent = async (title: string, text: string) => {
  if (navigator.share) {
    try {
      await navigator.share({
        title: title,
        text: text,
        url: window.location.href,
      });
    } catch (error) {
      if ((error as Error).name !== 'AbortError') {
        console.error('Error sharing:', error);
        copyToClipboard(text);
      }
    }
  } else {
    copyToClipboard(text);
  }
};

const copyToClipboard = (text: string) => {
  navigator.clipboard.writeText(text);
  alert('Content copied to clipboard for sharing!');
};
