/**
 * Expanded OER Catalog for Dare Digital Library
 * Includes resources from OpenStax, FAO, and WHO.
 */

export const OPENSTAX_EXPANDED = [
  {
    id: 'openstax-stats-1',
    title: 'Introductory Statistics',
    author_names: 'Barbara Illowsky, Susan Dean',
    publisher_name: 'OpenStax',
    faculty: 'STEM',
    subject: 'Statistics',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/IntroductoryStatistics-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=introductory-statistics',
    access_model: 'dare_access',
    year_published: 2013,
    description: 'Introductory Statistics follows scope and sequence requirements of a one-semester introduction to statistics course.',
    license_type: 'CC BY 4.0',
    total_downloads: 8500,
    average_rating: 4.6,
    page_count: 854
  },
  {
    id: 'openstax-precalc-1',
    title: 'Precalculus',
    author_names: 'Jay Abramson',
    publisher_name: 'OpenStax',
    faculty: 'STEM',
    subject: 'Mathematics',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/Precalculus-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=precalculus',
    access_model: 'dare_access',
    year_published: 2014,
    description: 'Precalculus is intended for college-level precalculus students.',
    license_type: 'CC BY 4.0',
    total_downloads: 7200,
    average_rating: 4.5,
    page_count: 1156
  },
  {
    id: 'openstax-alg-1',
    title: 'College Algebra',
    author_names: 'Jay Abramson',
    publisher_name: 'OpenStax',
    faculty: 'STEM',
    subject: 'Mathematics',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/CollegeAlgebra-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=college-algebra',
    access_model: 'dare_access',
    year_published: 2015,
    description: 'College Algebra provides a comprehensive exploration of algebraic principles.',
    license_type: 'CC BY 4.0',
    total_downloads: 9100,
    average_rating: 4.7,
    page_count: 1076
  },
  {
    id: 'openstax-micro-1',
    title: 'Microbiology',
    author_names: 'Nina Parker, Mark Schneegurt',
    publisher_name: 'OpenStax',
    faculty: 'Health',
    subject: 'Microbiology',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/Microbiology-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=microbiology',
    access_model: 'dare_access',
    year_published: 2016,
    description: 'Microbiology covers the scope and sequence requirements for a single-semester microbiology course.',
    license_type: 'CC BY 4.0',
    total_downloads: 6400,
    average_rating: 4.8,
    page_count: 1322
  },
  {
    id: 'openstax-ap-1',
    title: 'Anatomy and Physiology',
    author_names: 'J. Gordon Betts, Kelly A. Young',
    publisher_name: 'OpenStax',
    faculty: 'Health',
    subject: 'Medicine',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/AnatomyandPhysiology-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=anatomy-and-physiology',
    access_model: 'dare_access',
    year_published: 2013,
    description: 'Anatomy and Physiology is a dynamic textbook for the two-semester human anatomy and physiology course.',
    license_type: 'CC BY 4.0',
    total_downloads: 12000,
    average_rating: 4.9,
    page_count: 1418
  },
  {
    id: 'openstax-conbio-1',
    title: 'Concepts of Biology',
    author_names: 'Samantha Fowler, Rebecca Roush',
    publisher_name: 'OpenStax',
    faculty: 'STEM',
    subject: 'Biology',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/ConceptsofBiology-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=concepts-biology',
    access_model: 'dare_access',
    year_published: 2013,
    description: 'Concepts of Biology is designed for the single-semester introduction to biology course.',
    license_type: 'CC BY 4.0',
    total_downloads: 15000,
    average_rating: 4.7,
    page_count: 612
  },
  {
    id: 'openstax-nutri-1',
    title: 'Nutrition for Nurses',
    author_names: 'OpenStax',
    publisher_name: 'OpenStax',
    faculty: 'Health',
    subject: 'Nursing',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/NutritionforNurses-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=nutrition-nurses',
    access_model: 'dare_access',
    year_published: 2023,
    description: 'Nutrition for Nurses is designed to meet the scope and sequence of an introductory nutrition course for nursing students.',
    license_type: 'CC BY 4.0',
    total_downloads: 3200,
    average_rating: 4.8,
    page_count: 450
  },
  {
    id: 'openstax-acc-1',
    title: 'Principles of Accounting',
    author_names: 'Mitchell Franklin, Patty Graybeal',
    publisher_name: 'OpenStax',
    faculty: 'Business',
    subject: 'Accounting',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/PrinciplesofAccountingVolume1-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=principles-accounting-volume-1',
    access_model: 'dare_access',
    year_published: 2019,
    description: 'Principles of Accounting is designed to meet the scope and sequence requirements of a two-semester accounting course.',
    license_type: 'CC BY 4.0',
    total_downloads: 5600,
    average_rating: 4.5,
    page_count: 800
  },
  {
    id: 'openstax-buslaw-1',
    title: 'Business Law I Essentials',
    author_names: 'Mirande-Rae Werger',
    publisher_name: 'OpenStax',
    faculty: 'Law',
    subject: 'Law',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/BusinessLawIEssentials-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=business-law-i-essentials',
    access_model: 'dare_access',
    year_published: 2019,
    description: 'Business Law I Essentials is a brief introductory textbook designed to meet the scope and sequence requirements of courses on Business Law.',
    license_type: 'CC BY 4.0',
    total_downloads: 4100,
    average_rating: 4.4,
    page_count: 350
  },
  {
    id: 'openstax-bus-1',
    title: 'Introduction to Business',
    author_names: 'Lawrence J. Gitman, Carl McDaniel',
    publisher_name: 'OpenStax',
    faculty: 'Business',
    subject: 'Business',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/IntroductiontoBusiness-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=introduction-business',
    access_model: 'dare_access',
    year_published: 2018,
    description: 'Introduction to Business covers the scope and sequence of most introductory business courses.',
    license_type: 'CC BY 4.0',
    total_downloads: 7800,
    average_rating: 4.6,
    page_count: 650
  },
  {
    id: 'openstax-mgmt-1',
    title: 'Principles of Management',
    author_names: 'David S. Bright, Anastasios G. Cortes',
    publisher_name: 'OpenStax',
    faculty: 'Business',
    subject: 'Management',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/PrinciplesofManagement-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=principles-management',
    access_model: 'dare_access',
    year_published: 2019,
    description: 'Principles of Management is designed to meet the scope and sequence requirements of the introductory course on management.',
    license_type: 'CC BY 4.0',
    total_downloads: 6200,
    average_rating: 4.7,
    page_count: 550
  },
  {
    id: 'openstax-mktg-1',
    title: 'Principles of Marketing',
    author_names: 'OpenStax',
    publisher_name: 'OpenStax',
    faculty: 'Business',
    subject: 'Marketing',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/PrinciplesofMarketing-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=principles-marketing',
    access_model: 'dare_access',
    year_published: 2022,
    description: 'Principles of Marketing is designed to meet the scope and sequence requirements of the introductory course on marketing.',
    license_type: 'CC BY 4.0',
    total_downloads: 3500,
    average_rating: 4.5,
    page_count: 500
  },
  {
    id: 'openstax-polsci-1',
    title: 'Introduction to Political Science',
    author_names: 'Mark Alleman',
    publisher_name: 'OpenStax',
    faculty: 'Humanities',
    subject: 'Political Science',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/IntroductiontoPoliticalScience-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=introduction-political-science',
    access_model: 'dare_access',
    year_published: 2022,
    description: 'Introduction to Political Science provides a comprehensive overview of the field.',
    license_type: 'CC BY 4.0',
    total_downloads: 2800,
    average_rating: 4.6,
    page_count: 600
  },
  {
    id: 'openstax-phil-1',
    title: 'Introduction to Philosophy',
    author_names: 'Nathan Smith',
    publisher_name: 'OpenStax',
    faculty: 'Humanities',
    subject: 'Philosophy',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/IntroductiontoPhilosophy-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=introduction-philosophy',
    access_model: 'dare_access',
    year_published: 2022,
    description: 'Introduction to Philosophy provides a comprehensive overview of the field.',
    license_type: 'CC BY 4.0',
    total_downloads: 2500,
    average_rating: 4.7,
    page_count: 500
  }
];

export const AGRICULTURE_OER = [
  {
    id: 'fao-csa-1',
    title: 'Climate-Smart Agriculture Sourcebook',
    author_names: 'FAO',
    publisher_name: 'FAO',
    faculty: 'Agriculture',
    subject: 'Agriculture',
    cover_image_url: 'https://www.fao.org/3/i3325e/i3325e_cover.jpg',
    file_url: 'https://www.fao.org/3/i3325e/i3325e.pdf',
    access_model: 'dare_access',
    year_published: 2013,
    description: 'The Climate-Smart Agriculture Sourcebook provides guidance on how to implement CSA.',
    license_type: 'CC BY-NC-SA 3.0 IGO',
    total_downloads: 4500,
    average_rating: 4.8,
    page_count: 550
  },
  {
    id: 'fao-soils-1',
    title: 'Soils and Pulses',
    author_names: 'FAO',
    publisher_name: 'FAO',
    faculty: 'Agriculture',
    subject: 'Soil Science',
    cover_image_url: 'https://www.fao.org/3/i5555e/i5555e_cover.jpg',
    file_url: 'https://www.fao.org/3/i5555e/i5555e.pdf',
    access_model: 'dare_access',
    year_published: 2016,
    description: 'Soils and Pulses explores the relationship between soil health and pulse production.',
    license_type: 'CC BY-NC-SA 3.0 IGO',
    total_downloads: 3200,
    average_rating: 4.7,
    page_count: 120
  },
  {
    id: 'fao-postharvest-1',
    title: 'Post-Harvest Loss Reduction',
    author_names: 'FAO',
    publisher_name: 'FAO',
    faculty: 'Agriculture',
    subject: 'Agricultural Engineering',
    cover_image_url: 'https://www.fao.org/3/i1234e/i1234e_cover.jpg',
    file_url: 'https://www.fao.org/3/i1234e/i1234e.pdf',
    access_model: 'dare_access',
    year_published: 2020,
    description: 'Guidelines for reducing post-harvest losses in developing countries.',
    license_type: 'CC BY-NC-SA 3.0 IGO',
    total_downloads: 2800,
    average_rating: 4.6,
    page_count: 180
  },
  {
    id: 'fao-fisheries-1',
    title: 'State of World Fisheries 2024',
    author_names: 'FAO',
    publisher_name: 'FAO',
    faculty: 'Agriculture',
    subject: 'Fisheries',
    cover_image_url: 'https://www.fao.org/3/cc0461en/cc0461en_cover.jpg',
    file_url: 'https://www.fao.org/3/cc0461en/cc0461en.pdf',
    access_model: 'dare_access',
    year_published: 2024,
    description: 'The latest report on the status of world fisheries and aquaculture.',
    license_type: 'CC BY-NC-SA 3.0 IGO',
    total_downloads: 1500,
    average_rating: 4.9,
    page_count: 250
  },
  {
    id: 'fao-irrigation-1',
    title: 'Irrigation Water Management',
    author_names: 'FAO',
    publisher_name: 'FAO',
    faculty: 'Agriculture',
    subject: 'Irrigation',
    cover_image_url: 'https://www.fao.org/3/i5678e/i5678e_cover.jpg',
    file_url: 'https://www.fao.org/3/i5678e/i5678e.pdf',
    access_model: 'dare_access',
    year_published: 2018,
    description: 'Training manual on irrigation water management.',
    license_type: 'CC BY-NC-SA 3.0 IGO',
    total_downloads: 3900,
    average_rating: 4.7,
    page_count: 150
  },
  {
    id: 'fao-food-security-2023',
    title: 'The State of Food Security and Nutrition in the World 2023',
    author_names: 'FAO, IFAD, UNICEF, WFP and WHO',
    publisher_name: 'FAO',
    faculty: 'Agriculture',
    subject: 'Food Security',
    cover_image_url: 'https://www.fao.org/3/cc3017en/cc3017en_cover.jpg',
    file_url: 'https://www.fao.org/3/cc3017en/cc3017en.pdf',
    access_model: 'dare_access',
    year_published: 2023,
    description: 'Updates on the global food security status and nutrition.',
    license_type: 'CC BY-NC-SA 3.0 IGO',
    total_downloads: 5100,
    average_rating: 4.8,
    page_count: 300
  },
  {
    id: 'fao-save-grow',
    title: 'Save and Grow',
    author_names: 'FAO',
    publisher_name: 'FAO',
    faculty: 'Agriculture',
    subject: 'Sustainable Agriculture',
    cover_image_url: 'https://www.fao.org/3/i2215e/i2215e00.jpg',
    file_url: 'https://www.fao.org/3/i2215e/i2215e.pdf',
    access_model: 'dare_access',
    year_published: 2011,
    description: 'A policymaker\'s guide to the sustainable intensification of smallholder crop production.',
    license_type: 'CC BY-NC-SA 3.0 IGO',
    total_downloads: 4200,
    average_rating: 4.7,
    page_count: 110
  },
  {
    id: 'fao-organic-ag',
    title: 'Training Manual for Organic Agriculture',
    author_names: 'FAO',
    publisher_name: 'FAO',
    faculty: 'Agriculture',
    subject: 'Organic Farming',
    cover_image_url: 'https://www.fao.org/3/i4551e/i4551e_cover.jpg',
    file_url: 'https://www.fao.org/3/i4551e/i4551e.pdf',
    access_model: 'dare_access',
    year_published: 2015,
    description: 'A comprehensive training manual for organic agriculture.',
    license_type: 'CC BY-NC-SA 3.0 IGO',
    total_downloads: 3800,
    average_rating: 4.6,
    page_count: 220
  }
];

export const HEALTH_OER = [
  {
    id: 'who-hand-1',
    title: 'Hand Hygiene Guidelines',
    author_names: 'WHO',
    publisher_name: 'WHO',
    faculty: 'Health',
    subject: 'Public Health',
    cover_image_url: 'https://apps.who.int/iris/bitstream/handle/10665/44102/9789241597906_eng_cover.jpg',
    file_url: 'https://apps.who.int/iris/bitstream/handle/10665/44102/9789241597906_eng.pdf',
    access_model: 'dare_access',
    year_published: 2009,
    description: 'WHO guidelines on hand hygiene in health care.',
    license_type: 'CC BY-NC-SA 3.0 IGO',
    total_downloads: 12000,
    average_rating: 4.9,
    page_count: 270
  },
  {
    id: 'who-epi-1',
    title: 'Basic Epidemiology',
    author_names: 'R. Bonita, R. Beaglehole, T. Kjellström',
    publisher_name: 'WHO',
    faculty: 'Health',
    subject: 'Epidemiology',
    cover_image_url: 'https://apps.who.int/iris/bitstream/handle/10665/43541/9241547073_eng_cover.jpg',
    file_url: 'https://apps.who.int/iris/bitstream/handle/10665/43541/9241547073_eng.pdf',
    access_model: 'dare_access',
    year_published: 2006,
    description: 'Basic Epidemiology provides an introduction to the core principles and methods of epidemiology.',
    license_type: 'CC BY-NC-SA 3.0 IGO',
    total_downloads: 8500,
    average_rating: 4.8,
    page_count: 226
  },
  {
    id: 'who-tb-2023',
    title: 'Global Tuberculosis Report 2023',
    author_names: 'WHO',
    publisher_name: 'WHO',
    faculty: 'Health',
    subject: 'Infectious Diseases',
    cover_image_url: 'https://iris.who.int/bitstream/handle/10665/373828/9789240083851-eng.jpg',
    file_url: 'https://iris.who.int/bitstream/handle/10665/373828/9789240083851-eng.pdf',
    access_model: 'dare_access',
    year_published: 2023,
    description: 'Comprehensive and up-to-date assessment of the TB epidemic, and of progress in prevention, diagnosis and treatment.',
    license_type: 'CC BY-NC-SA 3.0 IGO',
    total_downloads: 6700,
    average_rating: 4.8,
    page_count: 350
  },
  {
    id: 'who-malaria-2023',
    title: 'World Malaria Report 2023',
    author_names: 'WHO',
    publisher_name: 'WHO',
    faculty: 'Health',
    subject: 'Infectious Diseases',
    cover_image_url: 'https://iris.who.int/bitstream/handle/10665/374472/9789240086173-eng.jpg',
    file_url: 'https://iris.who.int/bitstream/handle/10665/374472/9789240086173-eng.pdf',
    access_model: 'dare_access',
    year_published: 2023,
    description: 'Provides a comprehensive update on global and regional malaria data and trends.',
    license_type: 'CC BY-NC-SA 3.0 IGO',
    total_downloads: 5400,
    average_rating: 4.7,
    page_count: 300
  },
  {
    id: 'who-child-care',
    title: 'Pocket Book of Hospital Care for Children',
    author_names: 'WHO',
    publisher_name: 'WHO',
    faculty: 'Health',
    subject: 'Pediatrics',
    cover_image_url: 'https://iris.who.int/bitstream/handle/10665/81170/9789241548373_eng.jpg',
    file_url: 'https://iris.who.int/bitstream/handle/10665/81170/9789241548373_eng.pdf',
    access_model: 'dare_access',
    year_published: 2013,
    description: 'Guidelines for the management of common childhood illnesses.',
    license_type: 'CC BY-NC-SA 3.0 IGO',
    total_downloads: 9200,
    average_rating: 4.9,
    page_count: 438
  }
];

export const ENGINEERING_OER = [
  {
    id: 'openstax-phys-2',
    title: 'University Physics Volume 2',
    author_names: 'Samuel J. Ling, Jeff Sanny, William Moebs',
    publisher_name: 'OpenStax',
    faculty: 'Engineering',
    subject: 'Physics',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/UniversityPhysicsVolume2-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=university-physics-volume-2',
    access_model: 'dare_access',
    year_published: 2016,
    description: 'University Physics is a three-volume collection for calculus-based physics courses.',
    license_type: 'CC BY 4.0',
    total_downloads: 9500,
    average_rating: 4.7,
    page_count: 800
  },
  {
    id: 'openstax-phys-3',
    title: 'University Physics Volume 3',
    author_names: 'Samuel J. Ling, Jeff Sanny, William Moebs',
    publisher_name: 'OpenStax',
    faculty: 'Engineering',
    subject: 'Physics',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/UniversityPhysicsVolume3-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=university-physics-volume-3',
    access_model: 'dare_access',
    year_published: 2016,
    description: 'University Physics is a three-volume collection for calculus-based physics courses.',
    license_type: 'CC BY 4.0',
    total_downloads: 8200,
    average_rating: 4.6,
    page_count: 850
  },
  {
    id: 'openstax-orgchem-1',
    title: 'Organic Chemistry',
    author_names: 'John McMurry',
    publisher_name: 'OpenStax',
    faculty: 'Engineering',
    subject: 'Chemistry',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/OrganicChemistry-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=organic-chemistry',
    access_model: 'dare_access',
    year_published: 2023,
    description: 'Organic Chemistry provides a comprehensive overview of the field.',
    license_type: 'CC BY 4.0',
    total_downloads: 4500,
    average_rating: 4.8,
    page_count: 1200
  },
  {
    id: 'rice-elec-eng-1',
    title: 'Fundamentals of Electrical Engineering I',
    author_names: 'Don Johnson',
    publisher_name: 'Rice University',
    faculty: 'Engineering',
    subject: 'Electrical Engineering',
    cover_image_url: 'https://picsum.photos/seed/elec-eng/400/600',
    file_url: 'https://scholarship.rice.edu/bitstream/handle/1911/19171/FundElecEng.pdf',
    access_model: 'dare_access',
    year_published: 2016,
    description: 'The course focuses on the creation, manipulation, transmission, and reception of information by electronic means.',
    license_type: 'CC BY 4.0',
    total_downloads: 3100,
    average_rating: 4.5,
    page_count: 350
  }
];

export const EDUCATION_OER = [
  {
    id: 'openstax-colsucc-1',
    title: 'College Success',
    author_names: 'Amy Baldwin',
    publisher_name: 'OpenStax',
    faculty: 'Education',
    subject: 'Education',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/CollegeSuccess-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=college-success',
    access_model: 'dare_access',
    year_published: 2020,
    description: 'College Success is a comprehensive and contemporary resource that serves as a guide for students.',
    license_type: 'CC BY 4.0',
    total_downloads: 5200,
    average_rating: 4.7,
    page_count: 400
  },
  {
    id: 'openstax-lifespan-1',
    title: 'Lifespan Development',
    author_names: 'Rose M. Spielman',
    publisher_name: 'OpenStax',
    faculty: 'Education',
    subject: 'Psychology',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/LifespanDevelopment-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=lifespan-development',
    access_model: 'dare_access',
    year_published: 2023,
    description: 'Lifespan Development provides a comprehensive overview of the field.',
    license_type: 'CC BY 4.0',
    total_downloads: 3100,
    average_rating: 4.6,
    page_count: 650
  },
  {
    id: 'openstax-org-behavior',
    title: 'Organizational Behavior',
    author_names: 'J. Stewart Black, David S. Bright',
    publisher_name: 'OpenStax',
    faculty: 'Business',
    subject: 'Management',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/OrganizationalBehavior-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=organizational-behavior',
    access_model: 'dare_access',
    year_published: 2019,
    description: 'Organizational Behavior is designed to meet the scope and sequence requirements of the introductory course on organizational behavior.',
    license_type: 'CC BY 4.0',
    total_downloads: 4800,
    average_rating: 4.7,
    page_count: 700
  },
  {
    id: 'openstax-bus-ethics',
    title: 'Business Ethics',
    author_names: 'Stephen M. Byars, Kurt Stanberry',
    publisher_name: 'OpenStax',
    faculty: 'Business',
    subject: 'Business',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/BusinessEthics-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=business-ethics',
    access_model: 'dare_access',
    year_published: 2018,
    description: 'Business Ethics is designed to meet the scope and sequence requirements of the single-semester business ethics course.',
    license_type: 'CC BY 4.0',
    total_downloads: 3900,
    average_rating: 4.6,
    page_count: 450
  },
  {
    id: 'openstax-entrepreneurship',
    title: 'Entrepreneurship',
    author_names: 'David S. Bright, Anastasios G. Cortes',
    publisher_name: 'OpenStax',
    faculty: 'Business',
    subject: 'Business',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/Entrepreneurship-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=entrepreneurship',
    access_model: 'dare_access',
    year_published: 2020,
    description: 'Entrepreneurship covers the scope and sequence of most introductory entrepreneurship courses.',
    license_type: 'CC BY 4.0',
    total_downloads: 5500,
    average_rating: 4.8,
    page_count: 600
  },
  {
    id: 'openstax-am-gov',
    title: 'American Government 3e',
    author_names: 'Glen Krutz, Sylvie Waskiewicz',
    publisher_name: 'OpenStax',
    faculty: 'Humanities',
    subject: 'Political Science',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/AmericanGovernment3e-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=american-government-3e',
    access_model: 'dare_access',
    year_published: 2021,
    description: 'American Government 3e aligns with the topics and objectives of many government courses.',
    license_type: 'CC BY 4.0',
    total_downloads: 7100,
    average_rating: 4.5,
    page_count: 600
  },
  {
    id: 'openstax-writing-guide',
    title: 'Writing Guide with Handbook',
    author_names: 'Michelle Bachelor Robinson, Maria Jerskey',
    publisher_name: 'OpenStax',
    faculty: 'Humanities',
    subject: 'Writing',
    cover_image_url: 'https://assets.openstax.org/oscms-prodcms/media/documents/WritingGuidewithHandbook-OP_cover.jpg',
    file_url: 'https://openstax.org/download/pdf?book=writing-guide',
    access_model: 'dare_access',
    year_published: 2022,
    description: 'Writing Guide with Handbook aligns to the goals of first-year writing courses.',
    license_type: 'CC BY 4.0',
    total_downloads: 4300,
    average_rating: 4.7,
    page_count: 550
  }
];

export const ANDREWS_OER = [
  {
    id: 'andrews-rev-1',
    title: 'Revelation of Jesus Christ',
    author_names: 'Ranko Stefanovic',
    publisher_name: 'Andrews University Press',
    faculty: 'Humanities',
    subject: 'Theology',
    cover_image_url: 'https://picsum.photos/seed/revelation/400/600',
    file_url: '#',
    access_model: 'dare_access',
    year_published: 2002,
    description: 'A comprehensive verse-by-verse commentary on the book of Revelation, providing a text-focused and Christ-centered approach to biblical exegesis.',
    license_type: 'All Rights Reserved (Andrews University Press)',
    total_downloads: 1200,
    average_rating: 4.9,
    page_count: 670
  }
];

export const AI_OER = [
  {
    id: 'ai-poole-1',
    title: 'Artificial Intelligence: Foundations of Computational Agents',
    author_names: 'David L. Poole, Alan K. Mackworth',
    publisher_name: 'Cambridge University Press (Open Edition)',
    faculty: 'STEM',
    subject: 'Artificial Intelligence',
    cover_image_url: 'https://picsum.photos/seed/ai-foundations/400/600',
    file_url: 'https://artint.info/2e/html/ArtInt2e.html', // This is HTML, but we'll treat as resource
    access_model: 'dare_access',
    year_published: 2017,
    description: 'Comprehensive textbook on the science of artificial intelligence, focusing on the design of intelligent agents. Maps to BSC-AI-001, BSC-CS-001.',
    license_type: 'CC BY-NC-ND 4.0',
    total_downloads: 5400,
    average_rating: 4.8,
    page_count: 820,
    ai_level: 2,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001"]
  },
  {
    id: 'ai-nielsen-1',
    title: 'Neural Networks and Deep Learning',
    author_names: 'Michael Nielsen',
    publisher_name: 'Determination Press',
    faculty: 'STEM',
    subject: 'Deep Learning',
    cover_image_url: 'https://picsum.photos/seed/neural-nets/400/600',
    file_url: 'http://neuralnetworksanddeeplearning.com/',
    access_model: 'dare_access',
    year_published: 2015,
    description: 'Master the core concepts of neural networks and deep learning. Maps to BSC-AI-001, BSC-CS-001.',
    license_type: 'CC BY-NC 3.0',
    total_downloads: 8900,
    average_rating: 4.9,
    page_count: 210,
    ai_level: 2,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001"]
  },
  {
    id: 'ai-goodfellow-1',
    title: 'Deep Learning',
    author_names: 'Ian Goodfellow, Yoshua Bengio, Aaron Courville',
    publisher_name: 'MIT Press (Online Edition)',
    faculty: 'STEM',
    subject: 'Deep Learning',
    cover_image_url: 'https://picsum.photos/seed/deep-learning/400/600',
    file_url: 'https://www.deeplearningbook.org/',
    access_model: 'dare_access',
    year_published: 2016,
    description: 'The definitive textbook on deep learning, covering mathematical foundations and advanced research topics. Maps to BSC-AI-001.',
    license_type: 'Free Online Access',
    total_downloads: 15000,
    average_rating: 4.9,
    page_count: 800,
    ai_level: 3,
    zimche_programme_codes: ["BSC-AI-001"]
  }
];

export const AI_PRIORITY_OER = [
  {
    id: 'ai-drive-resource-1',
    title: "Living by the Code",
    author_names: "Dare Digital Library Contributor",
    publisher_name: "Google Drive Resource",
    faculty: 'STEM',
    subject: 'Artificial Intelligence',
    cover_image_url: 'https://picsum.photos/seed/livingbycode/400/600',
    file_url: "https://drive.google.com/file/d/1BVlQqck7BxpNP2-fUpog-XIC77yWrzBs/view?usp=drive_link",
    access_model: 'dare_access',
    year_published: 2024,
    description: "An insightful exploration of the principles and practices that define the future of software development and artificial intelligence.",
    license_type: "Dare Access",
    total_downloads: 0,
    average_rating: 0,
    ai_level: 1,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001", "DIP-DS-001", "HND-ICT-001", "BENG-COMP-001"],
    featured: true
  },
  {
    id: 'ai-think-python',
    title: "Think Python 2e",
    author_names: "Allen Downey",
    publisher_name: "Green Tea Press",
    faculty: 'STEM',
    subject: 'Artificial Intelligence',
    cover_image_url: 'https://picsum.photos/seed/python/400/600',
    file_url: "https://greenteapress.com/thinkpython2/thinkpython2.pdf",
    access_model: 'dare_access',
    year_published: 2015,
    description: "Entry point for every AI/CS student. Suitable for all 5 programmes and 1,530 students. Covers basic Python programming, data structures, and algorithms.",
    license_type: "CC BY-NC 4.0",
    total_downloads: 1530,
    average_rating: 4.7,
    ai_level: 1,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001", "DIP-DS-001", "HND-ICT-001", "BENG-COMP-001"]
  },
  {
    id: 'ai-data-science-handbook',
    title: "Python Data Science Handbook",
    author_names: "Jake VanderPlas",
    publisher_name: "O'Reilly (Open Edition)",
    faculty: 'STEM',
    subject: 'Data Science',
    cover_image_url: 'https://picsum.photos/seed/datascience/400/600',
    file_url: "https://jakevdp.github.io/PythonDataScienceHandbook/PythonDataScienceHandbook.pdf",
    access_model: 'dare_access',
    year_published: 2016,
    description: "Essential guide to data science in Python. Covers NumPy, Pandas, Matplotlib, and Scikit-Learn. Maps to BSC-CS-001, DIP-DS-001, HND-ICT-001.",
    license_type: "CC BY-NC-ND",
    total_downloads: 940,
    average_rating: 4.8,
    ai_level: 2,
    zimche_programme_codes: ["BSC-CS-001", "DIP-DS-001", "HND-ICT-001"]
  },
  {
    id: 'ai-islr',
    title: "Introduction to Statistical Learning 2e",
    author_names: "James, Witten, Hastie, Tibshirani",
    publisher_name: "Springer (Open Edition)",
    faculty: 'STEM',
    subject: 'Machine Learning',
    cover_image_url: 'https://picsum.photos/seed/statlearning/400/600',
    file_url: "https://www.statlearning.com/s/ISLR_Print2.pdf",
    access_model: 'dare_access',
    year_published: 2021,
    description: "Core ML textbook. Covers linear regression, classification, resampling methods, and tree-based methods. Maps to BSC-AI-001, BSC-CS-001.",
    license_type: "CC BY-NC 4.0",
    total_downloads: 660,
    average_rating: 4.9,
    ai_level: 2,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001"]
  },
  {
    id: 'ai-mml',
    title: "Mathematics for Machine Learning",
    author_names: "Deisenroth, Faisal, Ong",
    publisher_name: "Cambridge University Press",
    faculty: 'STEM',
    subject: 'Machine Learning',
    cover_image_url: 'https://picsum.photos/seed/mathml/400/600',
    file_url: "https://mml-book.github.io/book/mml-book.pdf",
    access_model: 'dare_access',
    year_published: 2020,
    description: "Foundational math for ML. Covers linear algebra, analytic geometry, matrix decompositions, vector calculus, and optimization. Maps to BSC-AI-001, BSC-CS-001.",
    license_type: "CC BY-NC-SA",
    total_downloads: 660,
    average_rating: 4.8,
    ai_level: 2,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001"]
  },
  {
    id: 'ai-d2l',
    title: "Dive into Deep Learning",
    author_names: "Zhang, Lipton, Li, Smola",
    publisher_name: "D2L.ai",
    faculty: 'STEM',
    subject: 'Deep Learning',
    cover_image_url: 'https://picsum.photos/seed/d2l/400/600',
    file_url: "https://d2l.ai/d2l-en.pdf",
    access_model: 'dare_access',
    year_published: 2023,
    description: "Advanced deep learning with PyTorch, MXNet, and TensorFlow. Indaba Africa endorsed. Maps to BSC-AI-001, BSC-CS-001, BENG-COMP-001.",
    license_type: "CC BY-SA 4.0",
    total_downloads: 1070,
    average_rating: 4.9,
    ai_level: 3,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001", "BENG-COMP-001"]
  },
  {
    id: 'ai-hands-on-ml',
    title: "Hands-On Machine Learning",
    author_names: "Aurélien Géron",
    publisher_name: "O'Reilly (Open Edition)",
    faculty: 'STEM',
    subject: 'Machine Learning',
    cover_image_url: 'https://picsum.photos/seed/handsonml/400/600',
    file_url: "https://github.com/ageron/handson-ml3",
    access_model: 'dare_access',
    year_published: 2022,
    description: "Practical guide to ML with Scikit-Learn, Keras, and TensorFlow. Has notebooks. Maps to BSC-AI-001, BSC-CS-001.",
    license_type: "AGPL v3",
    total_downloads: 1200,
    average_rating: 4.9,
    page_count: 850,
    ai_level: 2,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001"]
  },
  {
    id: 'ai-rl-sutton',
    title: "Reinforcement Learning: An Introduction",
    author_names: "Sutton, Barto",
    publisher_name: "MIT Press",
    faculty: 'STEM',
    subject: 'Reinforcement Learning',
    cover_image_url: 'https://picsum.photos/seed/rlsutton/400/600',
    file_url: "http://incompleteideas.net/book/the-book-2nd.html",
    access_model: 'dare_access',
    year_published: 2018,
    description: "The definitive guide to reinforcement learning. Maps to BSC-AI-001.",
    license_type: "MIT-style",
    total_downloads: 580,
    average_rating: 4.8,
    page_count: 550,
    ai_level: 3,
    zimche_programme_codes: ["BSC-AI-001"]
  },
  {
    id: 'ai-nlp-python',
    title: "Natural Language Processing with Python",
    author_names: "Bird, Klein, Loper",
    publisher_name: "O'Reilly",
    faculty: 'STEM',
    subject: 'NLP',
    cover_image_url: 'https://picsum.photos/seed/nlp/400/600',
    file_url: "https://www.nltk.org/book/",
    access_model: 'dare_access',
    year_published: 2009,
    description: "Introduction to NLP using NLTK. Maps to BSC-AI-001, BSC-CS-001.",
    license_type: "CC BY-NC-ND",
    total_downloads: 720,
    average_rating: 4.6,
    page_count: 500,
    ai_level: 2,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001"]
  },
  {
    id: 'ai-forecasting',
    title: "Forecasting: Principles and Practice 3e",
    author_names: "Hyndman, Athanasopoulos",
    publisher_name: "OTexts",
    faculty: 'STEM',
    subject: 'Forecasting',
    cover_image_url: 'https://picsum.photos/seed/forecasting/400/600',
    file_url: "https://otexts.com/fpp3/",
    access_model: 'dare_access',
    year_published: 2021,
    description: "Comprehensive guide to forecasting methods. Maps to BSC-AI-001, BSC-CS-001, HND-ICT-001.",
    license_type: "CC BY-NC-ND",
    total_downloads: 640,
    average_rating: 4.7,
    page_count: 400,
    ai_level: 2,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001", "HND-ICT-001"]
  },
  {
    id: 'ai-ethics-doab',
    title: "AI Ethics",
    author_names: "DOAB Dare Access",
    publisher_name: "DOAB",
    faculty: 'Humanities',
    subject: 'AI Ethics',
    cover_image_url: 'https://picsum.photos/seed/aiethics/400/600',
    file_url: "https://www.doabooks.org/",
    access_model: 'dare_access',
    year_published: 2023,
    description: "Exploration of ethical frameworks in AI, including African perspectives. Maps to ALL 5 programmes.",
    license_type: "CC BY 4.0",
    total_downloads: 450,
    average_rating: 4.5,
    page_count: 300,
    ai_level: 1,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001", "DIP-DS-001", "HND-ICT-001", "BENG-COMP-001"]
  },
  {
    id: 'ai-revolution-ojanpera',
    title: "AI Revolution: Mastering AI for Personal and Organizational Growth",
    author_names: "Tero Ojanperä",
    publisher_name: "River Publishers",
    faculty: 'STEM',
    subject: 'Artificial Intelligence',
    cover_image_url: 'https://picsum.photos/seed/airevolution/400/600',
    file_url: "https://www.riverpublishers.com/book_details.php?book_id=1037",
    access_model: 'licensed',
    year_published: 2024,
    description: "A practical guide to the AI revolution, covering generative AI technology, prompting strategies, and the impact on professions, productivity, and society.",
    license_type: "All Rights Reserved",
    total_downloads: 120,
    average_rating: 4.8,
    page_count: 154,
    ai_level: 1,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001", "MBA-AI-001"]
  },
  {
    id: 'ai-drive-resource-2',
    title: "Conversational AI with Rasa: Build, Test, and Deploy",
    author_names: "Dare Digital Library Contributor",
    publisher_name: "Google Drive Resource",
    faculty: 'STEM',
    subject: 'Artificial Intelligence',
    cover_image_url: 'https://picsum.photos/seed/rasa-ai/400/600',
    file_url: "https://drive.google.com/file/d/1JqAqhe7FGAJSDWFPD3Vn7smdU5h_E-CB/view?usp=drive_link",
    access_model: 'dare_access',
    year_published: 2024,
    description: "A comprehensive guide to building, testing, and deploying conversational AI applications using the Rasa framework.",
    license_type: "Open Access",
    total_downloads: 0,
    average_rating: 0,
    ai_level: 1,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001"]
  },
  {
    id: 'ai-drive-resource-3',
    title: "Deep Learning: Research and Applications",
    author_names: "Dare Digital Library Contributor",
    publisher_name: "Google Drive Resource",
    faculty: 'STEM',
    subject: 'Artificial Intelligence',
    cover_image_url: 'https://picsum.photos/seed/deeplearning-research/400/600',
    file_url: "https://drive.google.com/file/d/1ohkuflfwK2dkppVWPJVSVW2v-Aey5ZgK/view?usp=drive_link",
    access_model: 'dare_access',
    year_published: 2024,
    description: "An advanced exploration of deep learning architectures, research trends, and real-world applications in computer vision and NLP.",
    license_type: "Open Access",
    total_downloads: 0,
    average_rating: 0,
    ai_level: 3,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001", "BENG-COMP-001"]
  },
  {
    id: 'ai-drive-resource-4',
    title: "AI Resource 4",
    author_names: "Dare Digital Library Contributor",
    publisher_name: "Google Drive Resource",
    faculty: 'STEM',
    subject: 'Artificial Intelligence',
    cover_image_url: 'https://picsum.photos/seed/ai4/400/600',
    file_url: "https://drive.google.com/file/d/1yMJ27w992MmEwj301Q4K2Jdcy8IxzHS_/view?usp=drive_link",
    access_model: 'dare_access',
    year_published: 2024,
    description: "New AI resource from Google Drive.",
    license_type: "Open Access",
    total_downloads: 0,
    average_rating: 0,
    ai_level: 1,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001"]
  },
  {
    id: 'ai-drive-resource-5',
    title: "AI Resource 5",
    author_names: "Dare Digital Library Contributor",
    publisher_name: "Google Drive Resource",
    faculty: 'STEM',
    subject: 'Artificial Intelligence',
    cover_image_url: 'https://picsum.photos/seed/ai5/400/600',
    file_url: "https://drive.google.com/file/d/1EHZDruyxrzmJN0WE7ZKabryZua9_LSnJ/view?usp=drive_link",
    access_model: 'dare_access',
    year_published: 2024,
    description: "New AI resource from Google Drive.",
    license_type: "Open Access",
    total_downloads: 0,
    average_rating: 0,
    ai_level: 1,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001"]
  },
  {
    id: 'ai-drive-resource-6',
    title: "AI Resource 6",
    author_names: "Dare Digital Library Contributor",
    publisher_name: "Google Drive Resource",
    faculty: 'STEM',
    subject: 'Artificial Intelligence',
    cover_image_url: 'https://picsum.photos/seed/ai6/400/600',
    file_url: "https://drive.google.com/file/d/1RDAOSaoX4MjPS0ScmV7jpOcS28D1NN_h/view?usp=drive_link",
    access_model: 'dare_access',
    year_published: 2024,
    description: "New AI resource from Google Drive.",
    license_type: "Open Access",
    total_downloads: 0,
    average_rating: 0,
    ai_level: 1,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001"]
  },
  {
    id: 'ai-drive-resource-7',
    title: "AI Resource 7",
    author_names: "Dare Digital Library Contributor",
    publisher_name: "Google Drive Resource",
    faculty: 'STEM',
    subject: 'Artificial Intelligence',
    cover_image_url: 'https://picsum.photos/seed/ai7/400/600',
    file_url: "https://drive.google.com/file/d/1NZguQYDSxberpF_bEsYP4UTyI_WKJ597/view?usp=drive_link",
    access_model: 'dare_access',
    year_published: 2024,
    description: "New AI resource from Google Drive.",
    license_type: "Open Access",
    total_downloads: 0,
    average_rating: 0,
    ai_level: 1,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001"]
  },
  {
    id: 'ai-drive-resource-8',
    title: "AI Resource 8",
    author_names: "Dare Digital Library Contributor",
    publisher_name: "Google Drive Resource",
    faculty: 'STEM',
    subject: 'Artificial Intelligence',
    cover_image_url: 'https://picsum.photos/seed/ai8/400/600',
    file_url: "https://drive.google.com/file/d/12wfryH8GCLxI11tAFq5mYP2D9EAzjI4I/view?usp=drive_link",
    access_model: 'dare_access',
    year_published: 2024,
    description: "New AI resource from Google Drive.",
    license_type: "Open Access",
    total_downloads: 0,
    average_rating: 0,
    ai_level: 1,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001"]
  },
  {
    id: 'ai-drive-resource-9',
    title: "AI Resource 9",
    author_names: "Dare Digital Library Contributor",
    publisher_name: "Google Drive Resource",
    faculty: 'STEM',
    subject: 'Artificial Intelligence',
    cover_image_url: 'https://picsum.photos/seed/ai9/400/600',
    file_url: "https://drive.google.com/file/d/1KuVdeNphOskqHqtwRkHsILgjhM839SA5/view?usp=drive_link",
    access_model: 'dare_access',
    year_published: 2024,
    description: "New AI resource from Google Drive.",
    license_type: "Open Access",
    total_downloads: 0,
    average_rating: 0,
    ai_level: 1,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001"]
  },
  {
    id: 'ai-drive-resource-10',
    title: "The Self-Assembling Brain",
    author_names: "Peter Robin Hiesinger",
    publisher_name: "Princeton University Press",
    faculty: 'STEM',
    subject: 'Artificial Intelligence',
    cover_image_url: 'https://images.unbound.com/covers/9780691181226.jpg',
    file_url: "https://drive.google.com/file/d/1aZlqnU7IJ8iWJmJ1JDyhyMkiX6UqpDpY/view?usp=drive_link",
    access_model: 'dare_access',
    year_published: 2021,
    description: "How Neural Networks Grow Smarter. An insightful exploration of the biological and computational principles of brain development and artificial intelligence.",
    license_type: "Open Access",
    total_downloads: 120,
    average_rating: 4.8,
    ai_level: 2,
    zimche_programme_codes: ["BSC-AI-001", "BSC-CS-001"],
    featured: true
  }
];

export const AFRICAN_OER = [
  {
    id: 'zim-edu-50',
    title: 'Education 5.0: Transforming Higher Education in Zimbabwe',
    author_names: 'Ministry of Higher and Tertiary Education',
    publisher_name: 'Government of Zimbabwe',
    faculty: 'Education',
    subject: 'Education',
    cover_image_url: 'https://picsum.photos/seed/zim-edu/400/600',
    file_url: '#',
    year_published: 2019,
    description: 'The official policy document for Education 5.0 in Zimbabwe, focusing on Teaching, Research, Community Service, Innovation, and Industrialisation.',
    license_type: 'Public Domain',
    is_featured: true,
    is_zimbabwean: true,
    is_african: true,
    pillars: ["Teaching", "Research", "Community Service", "Innovation", "Industrialisation"]
  },
  {
    id: 'af-trade-1',
    title: 'The African Continental Free Trade Area: A Primer',
    author_names: 'UNECA',
    publisher_name: 'United Nations',
    faculty: 'Business',
    subject: 'Economics',
    cover_image_url: 'https://picsum.photos/seed/af-trade/400/600',
    file_url: 'https://www.uneca.org/sites/default/files/PublicationFiles/afcfta_primer_en.pdf',
    year_published: 2020,
    description: 'A comprehensive guide to the AfCFTA and its implications for African economies.',
    license_type: 'CC BY 3.0 IGO',
    is_featured: true,
    is_african: true,
    pillars: ["Research", "Innovation"]
  },
  {
    id: 'zim-history-1',
    title: 'A History of Zimbabwe',
    author_names: 'Alois S. Mlambo',
    publisher_name: 'Cambridge University Press (Open Access)',
    faculty: 'Humanities',
    subject: 'History',
    cover_image_url: 'https://picsum.photos/seed/zim-history/400/600',
    file_url: '#',
    year_published: 2014,
    description: 'A comprehensive history of Zimbabwe from the pre-colonial era to the present.',
    license_type: 'CC BY-NC-ND 4.0',
    is_featured: true,
    is_zimbabwean: true,
    is_african: true,
    pillars: ["Teaching", "Research"]
  }
];

export const ALL_ADDITIONAL_OER = [
  ...OPENSTAX_EXPANDED,
  ...AGRICULTURE_OER,
  ...HEALTH_OER,
  ...ENGINEERING_OER,
  ...EDUCATION_OER,
  ...ANDREWS_OER,
  ...AI_OER,
  ...AI_PRIORITY_OER,
  ...AFRICAN_OER
];
