-- ============================================================
-- Dare Assist — LibriVox Audiobook Seed
-- Generated: 2026-04-04T14:51:37.994Z
-- Source:    LibriVox.org (CC0 / Public Domain)
-- Schema:    Locked Dare Assist v21 books table
-- ============================================================
BEGIN;

INSERT INTO books (id, title, author_names, description, subject, subject_category, faculty, open_access_url, file_url, access_model, license_type, source_repository, openlibrary_id, publication_year, language, keywords, status, resource_type, content_type, format, in_app_reader, reader_type, is_african, is_african_authored, is_zimbabwean, is_featured, is_peer_reviewed, pillars, difficulty_level, target_audience, data_quality_score, last_verified_date, zimche_nqf_level, cover_image_url, publisher_name)
VALUES ('librivox-47', 'Count of Monte Cristo', 'Alexandre Dumas', 'The Count of Monte Cristo (French: Le Comte de Monte-Cristo ) is an adventure novel by Alexandre Dumas, père. It is often considered, along with The Three Musketeers , as Dumas''s most popular work. The writing of the work was completed in 1844. Like many of his novels, it is expanded from the plot outlines suggested by his collaborating ghostwriter Auguste Maquet. The story takes place in France, Italy, islands in the Mediterranean and the Levant during the historical events of 1815–1838 (from just before the Hundred Days through the reign of Louis-Philippe of France). The historical setting is a fundamental element of the book. It is primarily concerned with themes of justice, vengeance, mercy, and forgiveness, and is told in the style of an adventure story. (Summary from Wikipedia) This book contains alternate versions of a number of chapters – indicated by an alt after the file number. The Zip files contain both versions of these chapters. There are 2 versions of the M4Bs made , one containing the original files for these chapters (4 parts), the other containing the alternate files for the chapters (5 parts).', 'Education', 'Education & Teaching', 'Faculty of Education', 'https://librivox.org/the-count-of-monte-cristo-by-alexandre-dumas/', 'https://archive.org/compress/count_monte_cristo_0711_librivox/formats=64KBPS MP3&file=/count_monte_cristo_0711_librivox.zip', 'open_access', 'CC0', 'LibriVox', 'librivox:47', 1844, 'English', 'Count of Monte Cristo, Education, Faculty of Education, audiobook, librivox, public domain, open access, English, Dumas', 'published', 'audiobook', 'audio', 'MP3', FALSE, NULL, FALSE, FALSE, FALSE, FALSE, FALSE, '["Teaching and Learning","Community Engagement"]'::jsonb, 'intermediate', ARRAY['undergraduate', 'postgraduate', 'lecturer'], 7, '2026-04-04', 'L6', NULL, 'LibriVox')
ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        author_names = EXCLUDED.author_names,
        description = EXCLUDED.description,
        subject = EXCLUDED.subject,
        subject_category = EXCLUDED.subject_category,
        faculty = EXCLUDED.faculty,
        open_access_url = EXCLUDED.open_access_url,
        file_url = EXCLUDED.file_url,
        access_model = EXCLUDED.access_model,
        license_type = EXCLUDED.license_type,
        source_repository = EXCLUDED.source_repository,
        openlibrary_id = EXCLUDED.openlibrary_id,
        publication_year = EXCLUDED.publication_year,
        language = EXCLUDED.language,
        keywords = EXCLUDED.keywords,
        status = EXCLUDED.status,
        resource_type = EXCLUDED.resource_type,
        content_type = EXCLUDED.content_type,
        format = EXCLUDED.format,
        in_app_reader = EXCLUDED.in_app_reader,
        reader_type = EXCLUDED.reader_type,
        is_african = EXCLUDED.is_african,
        is_african_authored = EXCLUDED.is_african_authored,
        is_zimbabwean = EXCLUDED.is_zimbabwean,
        is_featured = EXCLUDED.is_featured,
        is_peer_reviewed = EXCLUDED.is_peer_reviewed,
        pillars = EXCLUDED.pillars,
        difficulty_level = EXCLUDED.difficulty_level,
        target_audience = EXCLUDED.target_audience,
        data_quality_score = EXCLUDED.data_quality_score,
        last_verified_date = EXCLUDED.last_verified_date,
        zimche_nqf_level = EXCLUDED.zimche_nqf_level,
        cover_image_url = EXCLUDED.cover_image_url,
        publisher_name = EXCLUDED.publisher_name,
        updated_at = now();

INSERT INTO books (id, title, author_names, description, subject, subject_category, faculty, open_access_url, file_url, access_model, license_type, source_repository, openlibrary_id, publication_year, language, keywords, status, resource_type, content_type, format, in_app_reader, reader_type, is_african, is_african_authored, is_zimbabwean, is_featured, is_peer_reviewed, pillars, difficulty_level, target_audience, data_quality_score, last_verified_date, zimche_nqf_level, cover_image_url, publisher_name)
VALUES ('librivox-52', 'Letters of Two Brides', 'Honoré de Balzac', 'Letters of Two Brides is an epistolary novel. The two brides are Louise de Chaulieu (Madame Gaston) and Renée de Maucombe (Madame l''Estorade). The women became friends during their education at a convent and upon leaving began a life-long correspondence. For a 17 year period, they exchange letters describing their lives. Michelle Crandall reads Renee’s letters, and Kara Shallenberg reads Louise’s. Letters from the men in their lives are read by Peter Yearsley, David Barnes, Denny Sayers, and Sean McKinley', 'Education', 'Education & Teaching', 'Faculty of Education', 'https://librivox.org/letters-of-two-brides-by-honore-de-balzac/', 'https://archive.org/compress/letters_brides_0709_librivox/formats=64KBPS MP3&file=/letters_brides_0709_librivox.zip', 'open_access', 'CC0', 'LibriVox', 'librivox:52', 1902, 'English', 'Letters of Two Brides, Education, Faculty of Education, audiobook, librivox, public domain, open access, English, Balzac', 'published', 'audiobook', 'audio', 'MP3', FALSE, NULL, FALSE, FALSE, FALSE, FALSE, FALSE, '["Teaching and Learning","Community Engagement"]'::jsonb, 'intermediate', ARRAY['undergraduate', 'postgraduate', 'lecturer'], 7, '2026-04-04', 'L6', NULL, 'LibriVox')
ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        author_names = EXCLUDED.author_names,
        description = EXCLUDED.description,
        subject = EXCLUDED.subject,
        subject_category = EXCLUDED.subject_category,
        faculty = EXCLUDED.faculty,
        open_access_url = EXCLUDED.open_access_url,
        file_url = EXCLUDED.file_url,
        access_model = EXCLUDED.access_model,
        license_type = EXCLUDED.license_type,
        source_repository = EXCLUDED.source_repository,
        openlibrary_id = EXCLUDED.openlibrary_id,
        publication_year = EXCLUDED.publication_year,
        language = EXCLUDED.language,
        keywords = EXCLUDED.keywords,
        status = EXCLUDED.status,
        resource_type = EXCLUDED.resource_type,
        content_type = EXCLUDED.content_type,
        format = EXCLUDED.format,
        in_app_reader = EXCLUDED.in_app_reader,
        reader_type = EXCLUDED.reader_type,
        is_african = EXCLUDED.is_african,
        is_african_authored = EXCLUDED.is_african_authored,
        is_zimbabwean = EXCLUDED.is_zimbabwean,
        is_featured = EXCLUDED.is_featured,
        is_peer_reviewed = EXCLUDED.is_peer_reviewed,
        pillars = EXCLUDED.pillars,
        difficulty_level = EXCLUDED.difficulty_level,
        target_audience = EXCLUDED.target_audience,
        data_quality_score = EXCLUDED.data_quality_score,
        last_verified_date = EXCLUDED.last_verified_date,
        zimche_nqf_level = EXCLUDED.zimche_nqf_level,
        cover_image_url = EXCLUDED.cover_image_url,
        publisher_name = EXCLUDED.publisher_name,
        updated_at = now();

INSERT INTO books (id, title, author_names, description, subject, subject_category, faculty, open_access_url, file_url, access_model, license_type, source_repository, openlibrary_id, publication_year, language, keywords, status, resource_type, content_type, format, in_app_reader, reader_type, is_african, is_african_authored, is_zimbabwean, is_featured, is_peer_reviewed, pillars, difficulty_level, target_audience, data_quality_score, last_verified_date, zimche_nqf_level, cover_image_url, publisher_name)
VALUES ('librivox-53', 'Bleak House', 'Charles Dickens', 'Bleak House is the ninth novel by Charles Dickens, published in 20 monthly parts between March 1852 and September 1853. It is widely held to be one of Dickens'' finest and most complete novels, containing one of the most vast, complex and engaging arrays of minor characters and sub-plots in his entire canon. Dickens tells all of these both through the narrative of the novel''s heroine, Esther Summerson, and as an omniscient narrator. Memorable characters include the menacing lawyer Tulkinghorn, the friendly but depressive John Jarndyce and the childish Harold Skimpole. The plot concerns a long-running legal dispute (Jarndyce and Jarndyce) which has far-reaching consequences for all involved. (Summary from Wikipedia)', 'Education', 'Education & Teaching', 'Faculty of Education', 'https://librivox.org/bleak-house-by-charles-dickens/', 'https://archive.org/compress/bleak_house_cl_librivox/formats=64KBPS MP3&file=/bleak_house_cl_librivox.zip', 'open_access', 'CC0', 'LibriVox', 'librivox:53', 1853, 'English', 'Bleak House, Education, Faculty of Education, audiobook, librivox, public domain, open access, English, Dickens', 'published', 'audiobook', 'audio', 'MP3', FALSE, NULL, FALSE, FALSE, FALSE, FALSE, FALSE, '["Teaching and Learning","Community Engagement"]'::jsonb, 'intermediate', ARRAY['undergraduate', 'postgraduate', 'lecturer'], 7, '2026-04-04', 'L6', NULL, 'LibriVox')
ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        author_names = EXCLUDED.author_names,
        description = EXCLUDED.description,
        subject = EXCLUDED.subject,
        subject_category = EXCLUDED.subject_category,
        faculty = EXCLUDED.faculty,
        open_access_url = EXCLUDED.open_access_url,
        file_url = EXCLUDED.file_url,
        access_model = EXCLUDED.access_model,
        license_type = EXCLUDED.license_type,
        source_repository = EXCLUDED.source_repository,
        openlibrary_id = EXCLUDED.openlibrary_id,
        publication_year = EXCLUDED.publication_year,
        language = EXCLUDED.language,
        keywords = EXCLUDED.keywords,
        status = EXCLUDED.status,
        resource_type = EXCLUDED.resource_type,
        content_type = EXCLUDED.content_type,
        format = EXCLUDED.format,
        in_app_reader = EXCLUDED.in_app_reader,
        reader_type = EXCLUDED.reader_type,
        is_african = EXCLUDED.is_african,
        is_african_authored = EXCLUDED.is_african_authored,
        is_zimbabwean = EXCLUDED.is_zimbabwean,
        is_featured = EXCLUDED.is_featured,
        is_peer_reviewed = EXCLUDED.is_peer_reviewed,
        pillars = EXCLUDED.pillars,
        difficulty_level = EXCLUDED.difficulty_level,
        target_audience = EXCLUDED.target_audience,
        data_quality_score = EXCLUDED.data_quality_score,
        last_verified_date = EXCLUDED.last_verified_date,
        zimche_nqf_level = EXCLUDED.zimche_nqf_level,
        cover_image_url = EXCLUDED.cover_image_url,
        publisher_name = EXCLUDED.publisher_name,
        updated_at = now();

INSERT INTO books (id, title, author_names, description, subject, subject_category, faculty, open_access_url, file_url, access_model, license_type, source_repository, openlibrary_id, publication_year, language, keywords, status, resource_type, content_type, format, in_app_reader, reader_type, is_african, is_african_authored, is_zimbabwean, is_featured, is_peer_reviewed, pillars, difficulty_level, target_audience, data_quality_score, last_verified_date, zimche_nqf_level, cover_image_url, publisher_name)
VALUES ('librivox-54', 'Penguin Island', 'Anatole France', 'The novel (original French title -- L''Île des Pingouins) is a satire on human nature. The first publication was in 1908. These penguins are mistaken for humans by the 97-year-old priest, Father Mael, because of his bad eyesight. He baptizes them, and once baptized, they have no choice but to become human. They take on human traits (build civilizations, go to war, etc.). The book is very funny and powerful. (Summary by Michael)', 'Education', 'Education & Teaching', 'Faculty of Education', 'https://librivox.org/penguin-island-by-anatole-france/', 'https://archive.org/compress/penguin_island_ms_librivox/formats=64KBPS MP3&file=/penguin_island_ms_librivox.zip', 'open_access', 'CC0', 'LibriVox', 'librivox:54', 1908, 'English', 'Penguin Island, Education, Faculty of Education, audiobook, librivox, public domain, open access, English, France', 'published', 'audiobook', 'audio', 'MP3', FALSE, NULL, FALSE, FALSE, FALSE, FALSE, FALSE, '["Teaching and Learning","Community Engagement"]'::jsonb, 'intermediate', ARRAY['undergraduate', 'postgraduate', 'lecturer'], 7, '2026-04-04', 'L6', NULL, 'LibriVox')
ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        author_names = EXCLUDED.author_names,
        description = EXCLUDED.description,
        subject = EXCLUDED.subject,
        subject_category = EXCLUDED.subject_category,
        faculty = EXCLUDED.faculty,
        open_access_url = EXCLUDED.open_access_url,
        file_url = EXCLUDED.file_url,
        access_model = EXCLUDED.access_model,
        license_type = EXCLUDED.license_type,
        source_repository = EXCLUDED.source_repository,
        openlibrary_id = EXCLUDED.openlibrary_id,
        publication_year = EXCLUDED.publication_year,
        language = EXCLUDED.language,
        keywords = EXCLUDED.keywords,
        status = EXCLUDED.status,
        resource_type = EXCLUDED.resource_type,
        content_type = EXCLUDED.content_type,
        format = EXCLUDED.format,
        in_app_reader = EXCLUDED.in_app_reader,
        reader_type = EXCLUDED.reader_type,
        is_african = EXCLUDED.is_african,
        is_african_authored = EXCLUDED.is_african_authored,
        is_zimbabwean = EXCLUDED.is_zimbabwean,
        is_featured = EXCLUDED.is_featured,
        is_peer_reviewed = EXCLUDED.is_peer_reviewed,
        pillars = EXCLUDED.pillars,
        difficulty_level = EXCLUDED.difficulty_level,
        target_audience = EXCLUDED.target_audience,
        data_quality_score = EXCLUDED.data_quality_score,
        last_verified_date = EXCLUDED.last_verified_date,
        zimche_nqf_level = EXCLUDED.zimche_nqf_level,
        cover_image_url = EXCLUDED.cover_image_url,
        publisher_name = EXCLUDED.publisher_name,
        updated_at = now();

INSERT INTO books (id, title, author_names, description, subject, subject_category, faculty, open_access_url, file_url, access_model, license_type, source_repository, openlibrary_id, publication_year, language, keywords, status, resource_type, content_type, format, in_app_reader, reader_type, is_african, is_african_authored, is_zimbabwean, is_featured, is_peer_reviewed, pillars, difficulty_level, target_audience, data_quality_score, last_verified_date, zimche_nqf_level, cover_image_url, publisher_name)
VALUES ('librivox-55', 'This Side of Paradise', 'F. Scott Fitzgerald', 'This Side of Paradise is the debut novel of F. Scott Fitzgerald. Published in 1920, and taking its title from a line of the Rupert Brooke poem Tiare Tahiti, the book examines the lives and morality of post-World War I youth. Its protagonist, Amory Blaine, is a wealthy and attractive Princeton University student who dabbles in literature and has a series of romances that eventually lead to his disillusionment. In his later novels, Fitzgerald would further develop the book''s theme of love warped by greed and status-seeking. (Summary from Wikipedia)', 'Education', 'Education & Teaching', 'Faculty of Education', 'https://librivox.org/this-side-of-paradise-by-f-scott-fitzgerald', 'https://archive.org/compress/this_side_paradise_librivox/formats=64KBPS MP3&file=/this_side_paradise_librivox.zip', 'open_access', 'CC0', 'LibriVox', 'librivox:55', 1920, 'English', 'This Side of Paradise, Education, Faculty of Education, audiobook, librivox, public domain, open access, English, Fitzgerald', 'published', 'audiobook', 'audio', 'MP3', FALSE, NULL, FALSE, FALSE, FALSE, FALSE, FALSE, '["Teaching and Learning","Community Engagement"]'::jsonb, 'intermediate', ARRAY['undergraduate', 'postgraduate', 'lecturer'], 7, '2026-04-04', 'L6', NULL, 'LibriVox')
ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        author_names = EXCLUDED.author_names,
        description = EXCLUDED.description,
        subject = EXCLUDED.subject,
        subject_category = EXCLUDED.subject_category,
        faculty = EXCLUDED.faculty,
        open_access_url = EXCLUDED.open_access_url,
        file_url = EXCLUDED.file_url,
        access_model = EXCLUDED.access_model,
        license_type = EXCLUDED.license_type,
        source_repository = EXCLUDED.source_repository,
        openlibrary_id = EXCLUDED.openlibrary_id,
        publication_year = EXCLUDED.publication_year,
        language = EXCLUDED.language,
        keywords = EXCLUDED.keywords,
        status = EXCLUDED.status,
        resource_type = EXCLUDED.resource_type,
        content_type = EXCLUDED.content_type,
        format = EXCLUDED.format,
        in_app_reader = EXCLUDED.in_app_reader,
        reader_type = EXCLUDED.reader_type,
        is_african = EXCLUDED.is_african,
        is_african_authored = EXCLUDED.is_african_authored,
        is_zimbabwean = EXCLUDED.is_zimbabwean,
        is_featured = EXCLUDED.is_featured,
        is_peer_reviewed = EXCLUDED.is_peer_reviewed,
        pillars = EXCLUDED.pillars,
        difficulty_level = EXCLUDED.difficulty_level,
        target_audience = EXCLUDED.target_audience,
        data_quality_score = EXCLUDED.data_quality_score,
        last_verified_date = EXCLUDED.last_verified_date,
        zimche_nqf_level = EXCLUDED.zimche_nqf_level,
        cover_image_url = EXCLUDED.cover_image_url,
        publisher_name = EXCLUDED.publisher_name,
        updated_at = now();

INSERT INTO books (id, title, author_names, description, subject, subject_category, faculty, open_access_url, file_url, access_model, license_type, source_repository, openlibrary_id, publication_year, language, keywords, status, resource_type, content_type, format, in_app_reader, reader_type, is_african, is_african_authored, is_zimbabwean, is_featured, is_peer_reviewed, pillars, difficulty_level, target_audience, data_quality_score, last_verified_date, zimche_nqf_level, cover_image_url, publisher_name)
VALUES ('librivox-56', 'Secret Garden', 'Frances Hodgson Burnett', 'Mary Lennox is a spoiled, middle-class, self-centered child who has been recently orphaned. She is accepted into the quiet and remote country house of an uncle, who has almost completely withdrawn into himself after the death of his wife. Mary gradually becomes drawn into the hidden side of the house: why does she hear the crying of a unseen child? Why is there an overgrown, walled garden, its door long locked? (Summary by Peter)', 'Education', 'Education & Teaching', 'Faculty of Education', 'https://librivox.org/the-secret-garden-by-frances-hodgson-burnett/', 'https://archive.org/compress/secret_garden_librivox/formats=64KBPS MP3&file=/secret_garden_librivox.zip', 'open_access', 'CC0', 'LibriVox', 'librivox:56', 1909, 'English', 'Secret Garden, Education, Faculty of Education, audiobook, librivox, public domain, open access, English, Burnett', 'published', 'audiobook', 'audio', 'MP3', FALSE, NULL, FALSE, FALSE, FALSE, FALSE, FALSE, '["Teaching and Learning","Community Engagement"]'::jsonb, 'intermediate', ARRAY['undergraduate', 'postgraduate', 'lecturer'], 7, '2026-04-04', 'L6', NULL, 'LibriVox')
ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        author_names = EXCLUDED.author_names,
        description = EXCLUDED.description,
        subject = EXCLUDED.subject,
        subject_category = EXCLUDED.subject_category,
        faculty = EXCLUDED.faculty,
        open_access_url = EXCLUDED.open_access_url,
        file_url = EXCLUDED.file_url,
        access_model = EXCLUDED.access_model,
        license_type = EXCLUDED.license_type,
        source_repository = EXCLUDED.source_repository,
        openlibrary_id = EXCLUDED.openlibrary_id,
        publication_year = EXCLUDED.publication_year,
        language = EXCLUDED.language,
        keywords = EXCLUDED.keywords,
        status = EXCLUDED.status,
        resource_type = EXCLUDED.resource_type,
        content_type = EXCLUDED.content_type,
        format = EXCLUDED.format,
        in_app_reader = EXCLUDED.in_app_reader,
        reader_type = EXCLUDED.reader_type,
        is_african = EXCLUDED.is_african,
        is_african_authored = EXCLUDED.is_african_authored,
        is_zimbabwean = EXCLUDED.is_zimbabwean,
        is_featured = EXCLUDED.is_featured,
        is_peer_reviewed = EXCLUDED.is_peer_reviewed,
        pillars = EXCLUDED.pillars,
        difficulty_level = EXCLUDED.difficulty_level,
        target_audience = EXCLUDED.target_audience,
        data_quality_score = EXCLUDED.data_quality_score,
        last_verified_date = EXCLUDED.last_verified_date,
        zimche_nqf_level = EXCLUDED.zimche_nqf_level,
        cover_image_url = EXCLUDED.cover_image_url,
        publisher_name = EXCLUDED.publisher_name,
        updated_at = now();

INSERT INTO books (id, title, author_names, description, subject, subject_category, faculty, open_access_url, file_url, access_model, license_type, source_repository, openlibrary_id, publication_year, language, keywords, status, resource_type, content_type, format, in_app_reader, reader_type, is_african, is_african_authored, is_zimbabwean, is_featured, is_peer_reviewed, pillars, difficulty_level, target_audience, data_quality_score, last_verified_date, zimche_nqf_level, cover_image_url, publisher_name)
VALUES ('librivox-57', 'Twenty Years After', 'Alexandre Dumas', 'Let''s continue the D''Artagnan Romances that we''ve already started with The Three Musketeers.', 'Education', 'Education & Teaching', 'Faculty of Education', 'https://librivox.org/twenty-years-after-by-alexandre-dumas/', 'https://archive.org/compress/twentyyearsafter_0904_librivox/formats=64KBPS MP3&file=/twentyyearsafter_0904_librivox.zip', 'open_access', 'CC0', 'LibriVox', 'librivox:57', 1856, 'English', 'Twenty Years After, Education, Faculty of Education, audiobook, librivox, public domain, open access, English, Dumas', 'published', 'audiobook', 'audio', 'MP3', FALSE, NULL, FALSE, FALSE, FALSE, FALSE, FALSE, '["Teaching and Learning","Community Engagement"]'::jsonb, 'intermediate', ARRAY['undergraduate', 'postgraduate', 'lecturer'], 7, '2026-04-04', 'L6', NULL, 'LibriVox')
ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        author_names = EXCLUDED.author_names,
        description = EXCLUDED.description,
        subject = EXCLUDED.subject,
        subject_category = EXCLUDED.subject_category,
        faculty = EXCLUDED.faculty,
        open_access_url = EXCLUDED.open_access_url,
        file_url = EXCLUDED.file_url,
        access_model = EXCLUDED.access_model,
        license_type = EXCLUDED.license_type,
        source_repository = EXCLUDED.source_repository,
        openlibrary_id = EXCLUDED.openlibrary_id,
        publication_year = EXCLUDED.publication_year,
        language = EXCLUDED.language,
        keywords = EXCLUDED.keywords,
        status = EXCLUDED.status,
        resource_type = EXCLUDED.resource_type,
        content_type = EXCLUDED.content_type,
        format = EXCLUDED.format,
        in_app_reader = EXCLUDED.in_app_reader,
        reader_type = EXCLUDED.reader_type,
        is_african = EXCLUDED.is_african,
        is_african_authored = EXCLUDED.is_african_authored,
        is_zimbabwean = EXCLUDED.is_zimbabwean,
        is_featured = EXCLUDED.is_featured,
        is_peer_reviewed = EXCLUDED.is_peer_reviewed,
        pillars = EXCLUDED.pillars,
        difficulty_level = EXCLUDED.difficulty_level,
        target_audience = EXCLUDED.target_audience,
        data_quality_score = EXCLUDED.data_quality_score,
        last_verified_date = EXCLUDED.last_verified_date,
        zimche_nqf_level = EXCLUDED.zimche_nqf_level,
        cover_image_url = EXCLUDED.cover_image_url,
        publisher_name = EXCLUDED.publisher_name,
        updated_at = now();

INSERT INTO books (id, title, author_names, description, subject, subject_category, faculty, open_access_url, file_url, access_model, license_type, source_repository, openlibrary_id, publication_year, language, keywords, status, resource_type, content_type, format, in_app_reader, reader_type, is_african, is_african_authored, is_zimbabwean, is_featured, is_peer_reviewed, pillars, difficulty_level, target_audience, data_quality_score, last_verified_date, zimche_nqf_level, cover_image_url, publisher_name)
VALUES ('librivox-59', 'Adventures of Huckleberry Finn', 'Mark Twain', 'Adventures of Huckleberry Finn (1884) by Mark Twain is one of the truly great American novels, beloved by children, adults, and literary critics alike. The book tells the story of “Huck” Finn (first introduced as Tom Sawyer’s sidekick in The Adventures of Tom Sawyer ), his friend Jim, and their journey down the Mississippi River on a raft. Both are on the run, Huck from his drunk and abusive father, and Jim as a runaway slave. As Huck and Jim drift down the river, they meet many colorful characters and have many great adventures. The true heart of the story, however, is the friendship between Huck and Jim. A constant theme throughout the book is Huck’s internal struggle between what he has been taught, that helping a runaway slave is a sin, and what he truly believes, that Jim is a good man and it couldn’t possibly be wrong to help him. Adventures of Huckleberry Finn was unique at the time of its publication (1884) because it is narrated by Huck himself and is written in the numerous dialects common in the area and time in which the book is set. Although the book was originally intended as a sequel to the children’s book The Adventures of Tom Sawyer , as Twain wrote Adventures of Huckleberry Finn it progressed into a more serious work. Twain’s views on slavery and other social issues of the time become clear through the words, thoughts, and actions of Huck Finn. The book has always been the subject of great controversy, and according to The American Library Association it was fifth on the list of most frequently challenged books in the 1990s. (Summary by Annie Coleman)', 'Education', 'Education & Teaching', 'Faculty of Education', 'https://librivox.org/the-adventures-of-huckleberry-finn-by-mark-twain/', 'https://archive.org/compress/huck_finn_librivox/formats=64KBPS MP3&file=/huck_finn_librivox.zip', 'open_access', 'CC0', 'LibriVox', 'librivox:59', 1884, 'English', 'Adventures of Huckleberry Finn, Education, Faculty of Education, audiobook, librivox, public domain, open access, English, Twain', 'published', 'audiobook', 'audio', 'MP3', FALSE, NULL, FALSE, FALSE, FALSE, FALSE, FALSE, '["Teaching and Learning","Community Engagement"]'::jsonb, 'intermediate', ARRAY['undergraduate', 'postgraduate', 'lecturer'], 7, '2026-04-04', 'L6', NULL, 'LibriVox')
ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        author_names = EXCLUDED.author_names,
        description = EXCLUDED.description,
        subject = EXCLUDED.subject,
        subject_category = EXCLUDED.subject_category,
        faculty = EXCLUDED.faculty,
        open_access_url = EXCLUDED.open_access_url,
        file_url = EXCLUDED.file_url,
        access_model = EXCLUDED.access_model,
        license_type = EXCLUDED.license_type,
        source_repository = EXCLUDED.source_repository,
        openlibrary_id = EXCLUDED.openlibrary_id,
        publication_year = EXCLUDED.publication_year,
        language = EXCLUDED.language,
        keywords = EXCLUDED.keywords,
        status = EXCLUDED.status,
        resource_type = EXCLUDED.resource_type,
        content_type = EXCLUDED.content_type,
        format = EXCLUDED.format,
        in_app_reader = EXCLUDED.in_app_reader,
        reader_type = EXCLUDED.reader_type,
        is_african = EXCLUDED.is_african,
        is_african_authored = EXCLUDED.is_african_authored,
        is_zimbabwean = EXCLUDED.is_zimbabwean,
        is_featured = EXCLUDED.is_featured,
        is_peer_reviewed = EXCLUDED.is_peer_reviewed,
        pillars = EXCLUDED.pillars,
        difficulty_level = EXCLUDED.difficulty_level,
        target_audience = EXCLUDED.target_audience,
        data_quality_score = EXCLUDED.data_quality_score,
        last_verified_date = EXCLUDED.last_verified_date,
        zimche_nqf_level = EXCLUDED.zimche_nqf_level,
        cover_image_url = EXCLUDED.cover_image_url,
        publisher_name = EXCLUDED.publisher_name,
        updated_at = now();

INSERT INTO books (id, title, author_names, description, subject, subject_category, faculty, open_access_url, file_url, access_model, license_type, source_repository, openlibrary_id, publication_year, language, keywords, status, resource_type, content_type, format, in_app_reader, reader_type, is_african, is_african_authored, is_zimbabwean, is_featured, is_peer_reviewed, pillars, difficulty_level, target_audience, data_quality_score, last_verified_date, zimche_nqf_level, cover_image_url, publisher_name)
VALUES ('librivox-64', 'Heart of Darkness', 'Joseph Conrad', 'Set in a time of oppressive colonisation, when large areas of the world were still unknown to Europe, and Africa was literally on maps and minds as a mysterious shadow, Heart of Darkness famously explores the rituals of civilisation and barbarism, and the frighteningly fine line between them. We get the tale through a classic unreliable narrator, relating as Marlow, a ship’s captain, tells how he was sent by the Company to retrieve the wayward Kurtz, and was shaken to discover the true depths of darkness in that creature’s, and in his own, soul. Conrad based the work closely on his own terrible experience in the Congo. This work has been reinterpreted and adapted into many modern forms, the most well known being the film Apocalypse Now. (Summary written by Marlo Dianne)', 'Education', 'Education & Teaching', 'Faculty of Education', 'https://librivox.org/heart-of-darkness-by-joseph-conrad', 'https://archive.org/compress/heart_of_darkness/formats=64KBPS MP3&file=/heart_of_darkness.zip', 'open_access', 'CC0', 'LibriVox', 'librivox:64', 1902, 'English', 'Heart of Darkness, Education, Faculty of Education, audiobook, librivox, public domain, open access, English, Conrad', 'published', 'audiobook', 'audio', 'MP3', FALSE, NULL, TRUE, TRUE, FALSE, FALSE, FALSE, '["Teaching and Learning","Community Engagement"]'::jsonb, 'intermediate', ARRAY['undergraduate', 'postgraduate', 'lecturer'], 7, '2026-04-04', 'L6', NULL, 'LibriVox')
ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        author_names = EXCLUDED.author_names,
        description = EXCLUDED.description,
        subject = EXCLUDED.subject,
        subject_category = EXCLUDED.subject_category,
        faculty = EXCLUDED.faculty,
        open_access_url = EXCLUDED.open_access_url,
        file_url = EXCLUDED.file_url,
        access_model = EXCLUDED.access_model,
        license_type = EXCLUDED.license_type,
        source_repository = EXCLUDED.source_repository,
        openlibrary_id = EXCLUDED.openlibrary_id,
        publication_year = EXCLUDED.publication_year,
        language = EXCLUDED.language,
        keywords = EXCLUDED.keywords,
        status = EXCLUDED.status,
        resource_type = EXCLUDED.resource_type,
        content_type = EXCLUDED.content_type,
        format = EXCLUDED.format,
        in_app_reader = EXCLUDED.in_app_reader,
        reader_type = EXCLUDED.reader_type,
        is_african = EXCLUDED.is_african,
        is_african_authored = EXCLUDED.is_african_authored,
        is_zimbabwean = EXCLUDED.is_zimbabwean,
        is_featured = EXCLUDED.is_featured,
        is_peer_reviewed = EXCLUDED.is_peer_reviewed,
        pillars = EXCLUDED.pillars,
        difficulty_level = EXCLUDED.difficulty_level,
        target_audience = EXCLUDED.target_audience,
        data_quality_score = EXCLUDED.data_quality_score,
        last_verified_date = EXCLUDED.last_verified_date,
        zimche_nqf_level = EXCLUDED.zimche_nqf_level,
        cover_image_url = EXCLUDED.cover_image_url,
        publisher_name = EXCLUDED.publisher_name,
        updated_at = now();

INSERT INTO books (id, title, author_names, description, subject, subject_category, faculty, open_access_url, file_url, access_model, license_type, source_repository, openlibrary_id, publication_year, language, keywords, status, resource_type, content_type, format, in_app_reader, reader_type, is_african, is_african_authored, is_zimbabwean, is_featured, is_peer_reviewed, pillars, difficulty_level, target_audience, data_quality_score, last_verified_date, zimche_nqf_level, cover_image_url, publisher_name)
VALUES ('librivox-65', 'Odyssey', 'Homer', 'The Odyssey is one of the two major ancient Greek epic poems (the other being the Iliad), attributed to the poet Homer. The poem is commonly dated to between 800 and 600 BC. The poem is, in part, a sequel to the Iliad, and concerns the events that befall the Greek hero Odysseus in his long journey back to his native land Ithaca after the fall of Troy. It takes Odysseus ten years to return to his native land of Ithaca after ten years of war; during his 20-year absence, his son Telemachus and his wife Penelope must deal with a group of unruly suitors who have moved into Odysseus'' home to compete for Penelope''s hand in marriage, since most have assumed that Odysseus has died. The poem is a fundamental text in the Western canon and continues to be read in both Homeric Greek and translations around the world. (Summary from Wikipedia)', 'Education', 'Education & Teaching', 'Faculty of Education', 'https://librivox.org/the-odyssey-by-homer/', 'https://archive.org/compress/odyssey_butler_librivox/formats=64KBPS MP3&file=/odyssey_butler_librivox.zip', 'open_access', 'CC0', 'LibriVox', 'librivox:65', 1900, 'English', 'Odyssey, Education, Faculty of Education, audiobook, librivox, public domain, open access, English, Homer', 'published', 'audiobook', 'audio', 'MP3', FALSE, NULL, FALSE, FALSE, FALSE, FALSE, FALSE, '["Teaching and Learning","Community Engagement"]'::jsonb, 'intermediate', ARRAY['undergraduate', 'postgraduate', 'lecturer'], 7, '2026-04-04', 'L6', NULL, 'LibriVox')
ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        author_names = EXCLUDED.author_names,
        description = EXCLUDED.description,
        subject = EXCLUDED.subject,
        subject_category = EXCLUDED.subject_category,
        faculty = EXCLUDED.faculty,
        open_access_url = EXCLUDED.open_access_url,
        file_url = EXCLUDED.file_url,
        access_model = EXCLUDED.access_model,
        license_type = EXCLUDED.license_type,
        source_repository = EXCLUDED.source_repository,
        openlibrary_id = EXCLUDED.openlibrary_id,
        publication_year = EXCLUDED.publication_year,
        language = EXCLUDED.language,
        keywords = EXCLUDED.keywords,
        status = EXCLUDED.status,
        resource_type = EXCLUDED.resource_type,
        content_type = EXCLUDED.content_type,
        format = EXCLUDED.format,
        in_app_reader = EXCLUDED.in_app_reader,
        reader_type = EXCLUDED.reader_type,
        is_african = EXCLUDED.is_african,
        is_african_authored = EXCLUDED.is_african_authored,
        is_zimbabwean = EXCLUDED.is_zimbabwean,
        is_featured = EXCLUDED.is_featured,
        is_peer_reviewed = EXCLUDED.is_peer_reviewed,
        pillars = EXCLUDED.pillars,
        difficulty_level = EXCLUDED.difficulty_level,
        target_audience = EXCLUDED.target_audience,
        data_quality_score = EXCLUDED.data_quality_score,
        last_verified_date = EXCLUDED.last_verified_date,
        zimche_nqf_level = EXCLUDED.zimche_nqf_level,
        cover_image_url = EXCLUDED.cover_image_url,
        publisher_name = EXCLUDED.publisher_name,
        updated_at = now();


COMMIT;

-- Total books seeded: 10
