import { useState, useEffect, useRef, useMemo } from 'react';
import { useParams, Link, useNavigate, Navigate } from 'react-router-dom';
import { motion } from 'motion/react';
import ReactMarkdown from 'react-markdown';
import InteractiveMarkdown from '../components/library/InteractiveMarkdown';
import { Document, Page, pdfjs } from 'react-pdf';
import 'react-pdf/dist/Page/AnnotationLayer.css';
import 'react-pdf/dist/Page/TextLayer.css';

// Configure PDF worker
pdfjs.GlobalWorkerOptions.workerSrc = `https://unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;

import { 
  ArrowLeft, 
  Maximize, 
  Minimize, 
  ExternalLink,
  Sparkles, 
  Send, 
  X, 
  MessageSquare,
  Loader2,
  ChevronLeft,
  ChevronRight,
  ZoomIn,
  ZoomOut,
  BookOpen,
  Download,
  Zap,
  HelpCircle,
  Lightbulb,
  CheckCircle,
  WifiOff,
  Wifi
} from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../hooks/useAuth';
import { useGamification, XP_REWARDS } from '../context/GamificationContext';
import { OPENSTAX_CURATED } from '../lib/transformBook';
import { ALL_ADDITIONAL_OER } from '../lib/oerCatalog';
import { openStaxService } from '../services/openStaxService';
import { geminiService } from '../services/geminiService';
import { offlineStorage } from '../lib/offlineStorage';

const ALL_OER = [...OPENSTAX_CURATED, ...ALL_ADDITIONAL_OER];
import styles from './Reader.module.css';

export default function Reader() {
  const { id } = useParams();
  const { user, institution } = useAuth();
  const { xp, streak, level, gainXp, updateBookProgress } = useGamification();
  const navigate = useNavigate();
  
  const [book, setBook] = useState(null);
  const [loading, setLoading] = useState(true);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [accessGranted, setAccessGranted] = useState(false);
  const [previewMode, setPreviewMode] = useState(false);
  const [viewUrl, setViewUrl] = useState('');
  const [dataSaverMode, setDataSaverMode] = useState(false);
  const [isOffline, setIsOffline] = useState(!navigator.onLine);
  const [remixedData, setRemixedData] = useState(null);
  
  // PDF Viewer State
  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);
  const [scale, setScale] = useState(1.0);
  const [useNativeViewer, setUseNativeViewer] = useState(true);
  const [forceShowViewer, setForceShowViewer] = useState(false);

  // Update book progress when page changes
  useEffect(() => {
    if (book?.id && numPages > 0) {
      const progress = Math.round((pageNumber / numPages) * 100);
      updateBookProgress(book.id, progress);
    }
  }, [pageNumber, numPages, book?.id, updateBookProgress]);

  // Memoize options to prevent unnecessary reloads
  const pdfOptions = useMemo(() => ({
    cMapUrl: `https://unpkg.com/pdfjs-dist@${pdfjs.version}/cmaps/`,
    cMapPacked: true,
    standardFontDataUrl: `https://unpkg.com/pdfjs-dist@${pdfjs.version}/standard_fonts/`,
  }), []);
  
  // AI Tutor State
  const [showAiSidebar, setShowAiSidebar] = useState(false);
  const [aiMessages, setAiMessages] = useState([
    { role: 'assistant', text: "Mhoro! I'm DARA, your personal AI Tutor. I'm here to help you master the material in this book. \n\nI can summarize chapters, explain complex concepts, or test your knowledge with a quick quiz. What shall we tackle first?" }
  ]);
  const [inputMessage, setInputMessage] = useState('');
  const [isAiThinking, setIsAiThinking] = useState(false);
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [isStudyMode, setIsStudyMode] = useState(false);
  const [studyView, setStudyView] = useState('content'); // 'content', 'flashcards', 'quiz'
  const [flashcards, setFlashcards] = useState([]);
  const [currentCardIndex, setCurrentCardIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [quiz, setQuiz] = useState(null);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [quizScore, setQuizScore] = useState(0);
  const [showResults, setShowResults] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [sessionId, setSessionId] = useState(null);
  const chatEndRef = useRef(null);

  const QUICK_QUESTIONS = [
    "Summarize this chapter",
    "Explain this concept",
    "Generate exam questions"
  ];

  const scrollToBottom = () => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  const [generatedBook, setGeneratedBook] = useState(null);
  const [isGeneratingBook, setIsGeneratingBook] = useState(false);

  const handleGenerateBook = async (bookData = book) => {
    setIsGeneratingBook(true);
    try {
      const context = `
        Title: ${bookData?.title}
        Author: ${bookData?.author_names}
        Description: ${bookData?.description}
        Subject: ${bookData?.subject}
      `;
      
      const prompt = `
        Create a comprehensive study guide for this book. 
        Structure it as a mini e-book with the following sections:
        1. Executive Summary
        2. Key Concepts & Definitions
        3. Chapter-by-Chapter Breakdown (estimated)
        4. Critical Analysis
        5. Review Questions
        
        Format the output in clean Markdown.
      `;

      const response = await geminiService.askQuestion(prompt, context);
      setGeneratedBook(response);
    } catch (err) {
      console.error('Error generating book:', err);
      alert('Failed to generate AI book. Please try again.');
    } finally {
      setIsGeneratingBook(false);
    }
  };

  useEffect(() => {
    scrollToBottom();
  }, [aiMessages]);

  useEffect(() => {
    async function fetchBookAndCheckAccess() {
      try {
        setLoading(true);
        let bookData = null;

        // Check offline storage first
        const offlineBook = offlineStorage.getOfflineBook(id);
        const existingRemix = offlineStorage.getRemix(id);
        if (existingRemix) setRemixedData(existingRemix);

        if (offlineBook) {
          bookData = offlineBook;
          setAccessGranted(true);
          setPreviewMode(false);
          setIsOffline(true);
        } else {
          const { data: dbBook, error: dbError } = await supabase
            .from('books')
            .select('*')
            .eq('id', id)
            .single();

          if (dbBook && !dbError) {
            bookData = {
              ...dbBook,
              file_path: dbBook.file_url,
              access_model: dbBook.access_model || 'dare_access',
              allow_download: true
            };
            setAccessGranted(true);
            setPreviewMode(false);
          } else if (id.startsWith('gutenberg-')) {
          const gId = id.replace('gutenberg-', '');
          try {
            const targetUrl = `https://gutendex.com/books/?ids=${gId}`;
            const { data: proxyResponse, error: proxyError } = await supabase.functions.invoke('external-proxy', {
              body: { url: targetUrl }
            });
            if (proxyError) throw proxyError;

            const data = proxyResponse.data;
            if (data.results && data.results.length > 0) {
              const gBook = data.results[0];
              bookData = {
                id: `gutenberg-${gBook.id}`,
                title: gBook.title,
                author_names: gBook.authors.map(a => a.name).join(', ') || 'Unknown Author',
                description: `Digitized by Project Gutenberg. Subjects: ${gBook.subjects.join(', ')}`,
                cover_image_url: gBook.formats['image/jpeg'] || 'https://picsum.photos/seed/book/400/600',
                file_url: gBook.formats['application/epub+zip'] || gBook.formats['text/html'] || gBook.formats['application/pdf'],
                file_path: gBook.formats['application/epub+zip'] || gBook.formats['text/html'] || gBook.formats['application/pdf'],
                language: gBook.languages[0] || 'English',
                source: 'Project Gutenberg',
                access_model: 'public_domain',
                allow_download: true
              };
              setAccessGranted(true);
              setPreviewMode(false);
            }
          } catch (err) {
            console.error('Error fetching Gutenberg book for reader:', err);
          }
        } else {
          const osBook = ALL_OER.find(b => b.id === id);
          if (osBook) {
            bookData = {
              ...osBook,
              file_path: osBook.file_url,
              access_model: 'open_access',
              allow_download: true
            };
            setAccessGranted(true);
            setPreviewMode(false);
          } else if (id.startsWith('openstax-')) {
            const identifier = id.replace('openstax-', '');
            try {
              const targetUrl = `https://archive.org/metadata/${identifier}`;
              const { data: proxyResponse, error: proxyError } = await supabase.functions.invoke('external-proxy', {
                body: { url: targetUrl }
              });
              if (proxyError) throw proxyError;

              const data = proxyResponse.data;
              if (data.metadata) {
                const meta = data.metadata;
                bookData = {
                  id: `openstax-${identifier}`,
                  title: meta.title,
                  author_names: Array.isArray(meta.creator) ? meta.creator.join(', ') : meta.creator || 'OpenStax',
                  description: meta.description || 'No description available.',
                  cover_image_url: `https://archive.org/services/img/${identifier}`,
                  file_url: `https://archive.org/download/${identifier}/${identifier}.pdf`,
                  file_path: `https://archive.org/download/${identifier}/${identifier}.pdf`,
                  language: meta.language || 'English',
                  source: 'OpenStax',
                  access_model: 'open_access',
                  allow_download: true
                };
                setAccessGranted(true);
                setPreviewMode(false);
              } else {
                throw new Error('OpenStax book metadata not found');
              }
            } catch (err) {
              console.error('Error fetching OpenStax metadata for reader:', err);
              throw err;
            }
          } else if (id.startsWith('ol-') || id.startsWith('olb-')) {
            const identifier = id.startsWith('ol-') ? id.replace('ol-', '/works/') : id.replace('olb-', '/books/');
            try {
              const targetUrl = `https://openlibrary.org${identifier}.json`;
              const { data: proxyResponse, error: proxyError } = await supabase.functions.invoke('external-proxy', {
                body: { url: targetUrl }
              });
              if (proxyError) throw proxyError;

              const data = proxyResponse.data;
              if (data) {
                bookData = {
                  id: id,
                  title: data.title,
                  author_names: 'Open Library Author',
                  description: data.description?.value || data.description || 'No description available.',
                  cover_image_url: data.covers ? `https://covers.openlibrary.org/b/id/${data.covers[0]}-L.jpg` : `https://picsum.photos/seed/${id}/400/600`,
                  file_url: `https://openlibrary.org${identifier}`,
                  file_path: `https://openlibrary.org${identifier}`,
                  language: 'English',
                  source: 'Open Library',
                  access_model: 'open_access',
                  allow_download: true
                };
                setAccessGranted(true);
                setPreviewMode(false);
              }
            } catch (err) {
              console.error('Error fetching Open Library metadata for reader:', err);
            }
          } else if (id.startsWith('arxiv-')) {
            const identifier = id.replace('arxiv-', '');
            try {
              const targetUrl = `https://export.arxiv.org/api/query?id_list=${identifier}`;
              const { data: proxyResponse, error: proxyError } = await supabase.functions.invoke('external-proxy', {
                body: { url: targetUrl }
              });
              if (proxyError) throw proxyError;

              const text = proxyResponse.data;
              const entryMatch = text.match(/<entry>([\s\S]*?)<\/entry>/);
              if (entryMatch) {
                const entry = entryMatch[1];
                const titleMatch = entry.match(/<title>(.*?)<\/title>/);
                const summaryMatch = entry.match(/<summary>(.*?)<\/summary>/);
                const authorMatch = [...entry.matchAll(/<name>(.*?)<\/name>/g)];
                const pdfMatch = entry.match(/<link title="pdf" href="(.*?)"/);
                
                bookData = {
                  id: id,
                  title: titleMatch ? titleMatch[1].replace(/\n/g, ' ').trim() : 'Unknown Title',
                  author_names: authorMatch.map(m => m[1]).join(', ') || 'Unknown Author',
                  description: summaryMatch ? summaryMatch[1].replace(/\n/g, ' ').trim() : 'No summary available.',
                  cover_image_url: `https://picsum.photos/seed/${id}/400/600`,
                  file_url: pdfMatch ? pdfMatch[1] : `https://arxiv.org/pdf/${identifier}.pdf`,
                  file_path: pdfMatch ? pdfMatch[1] : `https://arxiv.org/pdf/${identifier}.pdf`,
                  language: 'English',
                  source: 'arXiv Research',
                  access_model: 'open_access',
                  allow_download: true
                };
                setAccessGranted(true);
                setPreviewMode(false);
              }
            } catch (err) {
              console.error('Error fetching arXiv metadata for reader:', err);
            }
          } else {
            throw new Error('Book not found');
          }
        }
        }

        if (!bookData) {
          throw new Error('Book not found or failed to load');
        }

        setBook(bookData);
        
        // Requirement 3: External Resource Improvement
        // Automatically generate summary/quiz for external resources that can't be embedded
        const isExternal = bookData?.file_path && !bookData.file_path.toLowerCase().includes('.pdf') && !bookData.file_path.includes('.supabase.co/storage/v1/object/');
        if (isExternal && !generatedBook && !autoGenerated) {
          setAutoGenerated(true);
          handleGenerateBook(bookData);
        }

        // Update initial AI message with book context
        setAiMessages([
          { 
            role: 'assistant', 
            text: `Mhoro! I'm DARA, your AI Tutor. I see you're reading **${bookData.title}** by ${bookData.author_names || 'various authors'}. Great choice — this is one of our most popular resources. How can I help you master it? I can summarize sections, explain concepts, generate practice questions, or help you take structured notes.` 
          }
        ]);

        if (bookData?.file_path) {
          let finalUrl = bookData.file_path;
          const isSupabaseStorage = finalUrl.includes('.supabase.co/storage/v1/object/');
          if (isSupabaseStorage && user) {
            try {
              const urlParts = finalUrl.split('/books/');
              if (urlParts.length > 1) {
                const path = urlParts[1];
                const { data: signedData, error: signedError } = await supabase.storage
                  .from('books')
                  .createSignedUrl(path, 3600);
                if (!signedError && signedData?.signedUrl) {
                  finalUrl = signedData.signedUrl;
                }
              }
            } catch (err) {
              console.warn('Signed URL fallback:', err);
            }
          }
          setViewUrl(finalUrl);
          setUseNativeViewer(finalUrl.toLowerCase().includes('.pdf'));
        }

        if (user) {
          const updateSession = async () => {
            try {
              await supabase.from('reading_sessions').upsert({
                user_id: user.id,
                book_id: id,
                last_read_at: new Date().toISOString(),
              }, { onConflict: 'user_id, book_id' });
            } catch (err) {
              // Silent failure for background task
            }
          };
          updateSession();
        }

      } catch (err) {
        console.error('Error loading reader:', err);
      } finally {
        setLoading(false);
      }
    }
    fetchBookAndCheckAccess();
  }, [id, user, institution]);

  const [relatedBooks, setRelatedBooks] = useState([]);

  useEffect(() => {
    if (book?.subject) {
      const fetchRelated = async () => {
        try {
          const { data, error } = await supabase
            .from('books')
            .select('*')
            .eq('subject', book.subject)
            .neq('id', id)
            .limit(3);
          
          if (!error && data) {
            setRelatedBooks(data);
          }
        } catch (err) {
          console.warn('Related books fetch error:', err);
        }
      };
      fetchRelated();
    }
  }, [book?.subject, id]);

  const handleSendMessage = async (e, customMessage = null) => {
    if (e) e.preventDefault();
    const messageToSend = customMessage || inputMessage;
    
    if (!messageToSend.trim() || isAiThinking) return;

    setInputMessage('');
    setAiMessages(prev => [...prev, { role: 'user', text: messageToSend }]);
    setIsAiThinking(true);

    try {
      // 1. Ensure we have a session if user is logged in
      let currentSessionId = sessionId;
      if (user && !currentSessionId) {
        const { data: session, error: sError } = await supabase
          .from('dara_sessions')
          .insert({
            user_id: user.id,
            book_id: id,
            session_title: `Reading: ${book?.title || id}`
          })
          .select()
          .single();
        
        if (!sError && session) {
          currentSessionId = session.id;
          setSessionId(currentSessionId);
        }
      }

      // 2. Save user message to DB
      if (user && currentSessionId) {
        await supabase.from('dara_messages').insert({
          session_id: currentSessionId,
          user_id: user.id,
          role: 'user',
          content: messageToSend,
          books_referenced: [id]
        });
      }

      // 3. Get AI response
      const toc = book?.table_of_contents?.join('\n') || '';
      const context = `
        Book Title: ${book?.title}
        Author: ${book?.author_names}
        Section/Topic: ${book?.description?.substring(0, 200)}...
        Table of Contents:
        ${toc}
        Current Page: ${pageNumber}
        Mode: ${isStudyMode ? 'Study Mode (Focus on active recall, summaries, and quizzes)' : 'Read Mode'}
        
        Student Progress:
        - XP: ${xp}
        - Level: ${level}
        - Daily Streak: ${streak} days
        
        Task: Answer the student's question based on the provided book context.
        Student Question: ${messageToSend}
      `;
      
      const response = await geminiService.chat(context, aiMessages.map(m => ({
        role: m.role === 'assistant' ? 'ai' : 'user',
        text: m.text
      })));
      
      setAiMessages(prev => [...prev, { role: 'assistant', text: response }]);

      // 4. Save AI response to DB
      if (user && currentSessionId) {
        await supabase.from('dara_messages').insert({
          session_id: currentSessionId,
          user_id: user.id,
          role: 'assistant',
          content: response,
          books_referenced: [id]
        });
      }
    } catch (err) {
      console.error('AI Error:', err);
      setAiMessages(prev => [...prev, { role: 'assistant', text: 'Sorry, I encountered an error. Please try again.' }]);
    } finally {
      setIsAiThinking(false);
    }
  };

  const handleSummarize = async () => {
    if (isSummarizing || isAiThinking) return;
    
    setIsSummarizing(true);
    setIsAiThinking(true);
    setAiMessages(prev => [...prev, { role: 'user', text: 'Please summarize this book for me.' }]);

    try {
      const toc = book?.table_of_contents?.join('\n') || '';
      const context = `
        Title: ${book?.title}
        Author: ${book?.author_names}
        Description: ${book?.description}
        Table of Contents:
        ${toc}
      `;
      const response = await geminiService.summarize(context, "This is a book from the Dare Digital Library.");
      setAiMessages(prev => [...prev, { role: 'assistant', text: response }]);
    } catch (err) {
      console.error('Summarization Error:', err);
      setAiMessages(prev => [...prev, { role: 'assistant', text: 'Failed to generate summary. Please try again.' }]);
    } finally {
      setIsSummarizing(false);
      setIsAiThinking(false);
    }
  };

  const clearChat = () => {
    const greeting = book 
      ? `Mhoro! I'm DARA, your AI Tutor. I see you're reading **${book.title}** by ${book.author_names || 'various authors'}. Great choice — this is one of our most popular resources. How can I help you master it? I can summarize sections, explain concepts, generate practice questions, or help you take structured notes.`
      : "Mhoro! I'm DARA, your personal AI Tutor. I'm here to help you master the material in this book. \n\nI can summarize chapters, explain complex concepts, or test your knowledge with a quick quiz. What shall we tackle first?";
    
    setAiMessages([
      { role: 'assistant', text: greeting }
    ]);
  };

  const handleDownload = () => {
    if (!viewUrl) return;
    
    // Create a temporary link and trigger download
    const link = document.createElement('a');
    link.href = viewUrl;
    link.setAttribute('download', `${book?.title || 'document'}.pdf`);
    link.setAttribute('target', '_blank'); // Fallback for some browsers
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleSaveOffline = () => {
    if (!book) return;
    const success = offlineStorage.saveBookOffline(book.id, book);
    if (success) {
      setIsOffline(true);
      alert('Book saved for offline access!');
    }
  };

  const toggleDataSaver = () => {
    setDataSaverMode(!dataSaverMode);
    if (!dataSaverMode && !generatedBook) {
      handleGenerateBook(book);
    }
  };

  const handleInteractiveAction = (type, data) => {
    if (!showAiSidebar) setShowAiSidebar(true);
    
    let prompt = '';
    const text = typeof data === 'string' ? data : data.question;

    switch (type) {
      case 'explain':
        prompt = `Explain this concept more clearly: "${text}"`;
        break;
      case 'simplify':
        prompt = `Simplify this explanation for a beginner: "${text}"`;
        break;
      case 'quiz':
        prompt = `Generate a quick quiz question based on this section: "${text}"`;
        break;
      case 'answer':
        prompt = `Provide a detailed answer for this question: "${text}"`;
        break;
      case 'hint':
        prompt = `Give me a small hint for this question, but don't give the full answer yet: "${text}"`;
        break;
      case 'ask':
        prompt = `Tell me more about this: "${text}"`;
        break;
      case 'check_answer':
        prompt = `I'm trying to answer the question: "${data.question}". My answer is: "${data.userAnswer}". Please evaluate my answer, provide feedback, and explain the correct answer if I'm wrong.`;
        gainXp(XP_REWARDS.ANSWER_QUESTION, 'Answered Question');
        break;
      default:
        prompt = typeof data === 'string' ? data : data.question;
    }
    
    handleSendMessage(null, prompt);
  };

  const handleStudyAction = async (type) => {
    setStudyView(type);
    if (type === 'flashcards') {
      setIsLoading(true);
      try {
        const prompt = `Generate 5 flashcards for the book "${book.title}". Each card should have a "front" (question/term) and a "back" (answer/definition). Return as a JSON array of objects.`;
        const response = await geminiService.chat(prompt, [], { responseMimeType: 'application/json' });
        const cards = JSON.parse(response);
        setFlashcards(cards);
        setCurrentCardIndex(0);
        setIsFlipped(false);
      } catch (error) {
        console.error("Flashcard generation error:", error);
      } finally {
        setIsLoading(false);
      }
    } else if (type === 'quiz') {
      setIsLoading(true);
      try {
        const prompt = `Generate a 5-question multiple choice quiz for the book "${book.title}". Each question should have 4 options (A, B, C, D) and a "correctAnswer" (letter). Return as a JSON object with a "questions" array.`;
        const response = await geminiService.chat(prompt, [], { responseMimeType: 'application/json' });
        const quizData = JSON.parse(response);
        setQuiz(quizData);
        setCurrentQuestionIndex(0);
        setQuizScore(0);
        setShowResults(false);
      } catch (error) {
        console.error("Quiz generation error:", error);
      } finally {
        setIsLoading(false);
      }
    } else if (type === 'summary') {
      handleSendMessage(null, "Generate a concise summary of the current section");
      gainXp(XP_REWARDS.READ_SUMMARY, 'Read Summary');
      setStudyView('content');
    } else if (type === 'simplify') {
      handleSendMessage(null, "Simplify the main concepts of this section for a beginner");
      gainXp(XP_REWARDS.READ_SUMMARY, 'Simplified Concepts');
      setStudyView('content');
    }
  };

  const handleQuizAnswer = (selectedOption) => {
    if (selectedOption === quiz.questions[currentQuestionIndex].correctAnswer) {
      setQuizScore(prev => prev + 1);
    }
    
    if (currentQuestionIndex < quiz.questions.length - 1) {
      setCurrentQuestionIndex(prev => prev + 1);
    } else {
      setShowResults(true);
      gainXp(XP_REWARDS.COMPLETE_QUIZ, 'Completed Quiz');
    }
  };

  const renderStudyContent = () => {
    if (studyView === 'flashcards' && flashcards.length > 0) {
      const card = flashcards[currentCardIndex];
      return (
        <div className={styles.flashcardContainer}>
          <div className={styles.flashcardHeader}>
            <h3>Flashcards</h3>
            <span>{currentCardIndex + 1} / {flashcards.length}</span>
            <button onClick={() => setStudyView('content')} className={styles.closeStudyBtn}>Exit</button>
          </div>
          <div className={styles.flashcardWrapper}>
            <motion.div 
              className={`${styles.flashcard} ${isFlipped ? styles.flipped : ''}`}
              onClick={() => setIsFlipped(!isFlipped)}
            >
              <div className={styles.flashcardFront}>
                <p>{card.front}</p>
                <span className={styles.flipHint}>Click to flip</span>
              </div>
              <div className={styles.flashcardBack}>
                <p>{card.back}</p>
                <span className={styles.flipHint}>Click to flip</span>
              </div>
            </motion.div>
          </div>
          <div className={styles.flashcardControls}>
            <button 
              className={styles.navBtn}
              disabled={currentCardIndex === 0}
              onClick={() => { setCurrentCardIndex(prev => prev - 1); setIsFlipped(false); }}
            >
              <ChevronLeft size={20} />
            </button>
            <button 
              className={styles.navBtn}
              disabled={currentCardIndex === flashcards.length - 1}
              onClick={() => { setCurrentCardIndex(prev => prev + 1); setIsFlipped(false); }}
            >
              <ChevronRight size={20} />
            </button>
          </div>
        </div>
      );
    }

    if (studyView === 'quiz' && quiz) {
      if (showResults) {
        return (
          <div className={styles.quizResults}>
            <div className={styles.resultsHeader}>
              <Sparkles size={32} className={styles.aiIcon} />
              <h3>Quiz Complete!</h3>
            </div>
            <div className={styles.scoreCircle}>
              <span className={styles.scoreNumber}>{quizScore}</span>
              <span className={styles.scoreTotal}>/ {quiz.questions.length}</span>
            </div>
            <p className={styles.scoreText}>
              {quizScore === quiz.questions.length ? "Perfect score! You've mastered this section." : 
               quizScore >= quiz.questions.length / 2 ? "Good job! Keep studying to master the rest." : 
               "Keep going! Review the content and try again."}
            </p>
            <div className={styles.resultsActions}>
              <button onClick={() => handleStudyAction('quiz')} className={styles.retryQuizBtn}>Retry Quiz</button>
              <button onClick={() => setStudyView('content')} className={styles.exitQuizBtn}>Back to Reading</button>
            </div>
          </div>
        );
      }

      const question = quiz.questions[currentQuestionIndex];
      return (
        <div className={styles.quizContainer}>
          <div className={styles.quizProgress}>
            <span>Question {currentQuestionIndex + 1} of {quiz.questions.length}</span>
            <div className={styles.progressBar}>
              <div className={styles.progressFill} style={{ width: `${((currentQuestionIndex + 1) / quiz.questions.length) * 100}%` }}></div>
            </div>
          </div>
          <div className={styles.quizQuestionCard}>
            <h3 className={styles.questionText}>{question.question}</h3>
            <div className={styles.optionsGrid}>
              {['A', 'B', 'C', 'D'].map(letter => (
                <button 
                  key={letter}
                  className={styles.optionBtn}
                  onClick={() => handleQuizAnswer(letter)}
                >
                  <span className={styles.optionLetter}>{letter}</span>
                  {question.options[letter] || question.options[letter.toLowerCase()]}
                </button>
              ))}
            </div>
          </div>
          <button onClick={() => setStudyView('content')} className={styles.cancelQuizBtn}>Cancel Quiz</button>
        </div>
      );
    }

    return (
      <InteractiveMarkdown 
        content={generatedBook} 
        onAction={handleInteractiveAction}
        bookTitle={book?.title}
      />
    );
  };

  const toggleFullscreen = () => {
    try {
      if (!document.fullscreenElement) {
        if (document.documentElement.requestFullscreen) {
          document.documentElement.requestFullscreen().catch(err => {
            console.warn('Fullscreen request failed:', err);
          });
        }
        setIsFullscreen(true);
      } else {
        if (document.exitFullscreen) {
          document.exitFullscreen();
        }
        setIsFullscreen(false);
      }
    } catch (err) {
      console.warn('Fullscreen API error:', err);
      setIsFullscreen(!isFullscreen); // Fallback toggle
    }
  };

  if (loading) {
    return (
      <div className={styles.loadingContainer}>
        <div className={styles.spinner}></div>
        <p>Loading document...</p>
      </div>
    );
  }

  if (!book) {
    return (
      <div className={styles.errorContainer}>
        <h2>Book Not Found</h2>
        <p>We couldn't load this book. It may be unavailable or there might be a network issue.</p>
        <button onClick={() => navigate(-1)} className={styles.backLink} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, font: 'inherit' }}>Go Back</button>
      </div>
    );
  }

  if (!accessGranted) {
    return (
      <div className={styles.errorContainer}>
        <h2>Access Denied</h2>
        <p>You do not have permission to view this document.</p>
        <Link to={`/book/${id}`} className={styles.backLink}>Go back to details</Link>
      </div>
    );
  }

  return (
    <div className={`${styles.readerContainer} ${isFullscreen ? styles.fullscreen : ''}`}>
      {/* Preview Banner */}
      {previewMode && (
        <div className={styles.previewBanner}>
          <span>Preview Mode — Showing first 25 pages only</span>
          <Link to={`/book/${id}`} className={styles.upgradeLink}>
            Get Full Access
          </Link>
        </div>
      )}

      {/* Toolbar */}
      <div className={styles.toolbar}>
        <div className={styles.toolbarLeft}>
          <button 
            onClick={() => {
              if (book?.publisher_name === 'OpenStax' || book?.source === 'OpenStax') {
                navigate('/library');
              } else if (book?.id?.startsWith('res-')) {
                navigate('/research');
              } else if (book?.subject?.toLowerCase().includes('artificial intelligence') || book?.id?.startsWith('ai-')) {
                navigate('/ai-textbooks');
              } else {
                navigate('/library');
              }
            }} 
            className={styles.backBtn}
          >
            <ArrowLeft size={20} />
          </button>
          <h1 className={styles.title}>{book.title}</h1>
        </div>
        
        <div className={styles.toolbarRight}>
          <button 
            onClick={() => setIsStudyMode(!isStudyMode)}
            className={`${styles.studyToggle} ${isStudyMode ? styles.activeStudyToggle : ''}`}
            title={isStudyMode ? "Switch to Read Mode" : "Switch to Study Mode"}
          >
            <BookOpen size={18} />
            <span>{isStudyMode ? 'STUDY MODE' : 'READ MODE'}</span>
          </button>
          
          <button 
            onClick={toggleDataSaver} 
            className={`${styles.toolBtn} ${dataSaverMode ? styles.activeDataSaver : ''}`}
            title={dataSaverMode ? "Switch to Standard Mode" : "Enable Data Saver Mode"}
          >
            <div className={styles.dataSaverIcon}>
              <span className={styles.dataSaverText}>DATA SAVER</span>
            </div>
          </button>
          {book?.allow_download && (
            <div className="flex items-center gap-2">
              <button 
                onClick={handleSaveOffline} 
                className={`${styles.toolBtn} ${isOffline ? styles.activeTool : ''}`} 
                title={isOffline ? "Saved Offline" : "Save for Offline"}
              >
                {isOffline ? <Wifi size={20} className="text-green-500" /> : <WifiOff size={20} />}
              </button>
              <button onClick={handleDownload} className={styles.toolBtn} title="Download PDF">
                <Download size={20} />
              </button>
            </div>
          )}
          <button 
            onClick={() => setShowAiSidebar(!showAiSidebar)} 
            className={`${styles.toolBtn} ${showAiSidebar ? styles.activeTool : ''}`} 
            title="AI Tutor"
          >
            <Sparkles size={20} />
          </button>
          <button onClick={toggleFullscreen} className={styles.toolBtn} title="Toggle Fullscreen">
            {isFullscreen ? <Minimize size={20} /> : <Maximize size={20} />}
          </button>
        </div>
      </div>

      {/* PDF Viewer & Sidebar */}
      <div className={styles.mainContent}>
        {/* REMIX OVERLAY */}
        {remixedData && (
          <div className="absolute top-20 left-1/2 -translate-x-1/2 z-50 w-full max-w-2xl px-4 pointer-events-none">
            <motion.div 
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-soil/95 backdrop-blur-md text-white p-4 rounded-2xl shadow-2xl border border-white/20 pointer-events-auto"
            >
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                  <Sparkles size={16} className="text-accent" />
                  <span className="text-[10px] font-black uppercase tracking-widest">Zim-Curriculum Remix Active</span>
                </div>
                <button onClick={() => setRemixedData(null)} className="text-white/50 hover:text-white">
                  <X size={14} />
                </button>
              </div>
              <p className="text-xs font-bold leading-tight line-clamp-2 italic opacity-90">
                "{remixedData.zimSummary}"
              </p>
            </motion.div>
          </div>
        )}
        
        <div className={styles.viewerContent}>
          {dataSaverMode ? (
            <div className={styles.dataSaverView}>
              <div className={styles.dataSaverHeader}>
                <div className={styles.dataSaverTitle}>
                  <Sparkles size={20} className={styles.aiIcon} />
                  <h2>Data Saver Mode: AI Study Guide</h2>
                </div>
                <p className={styles.dataSaverHint}>PDF disabled to save data. Reading AI-generated summary.</p>
              </div>
              <div className={styles.generatedBookContent}>
                {isGeneratingBook ? (
                  <div className={styles.generatingState}>
                    <Loader2 size={48} className={styles.spin} />
                    <h3>Generating Study Guide...</h3>
                    <p>DARA is analyzing the book to save your data budget.</p>
                  </div>
                ) : generatedBook ? (
                  <div className="markdown-body">
                    <InteractiveMarkdown 
                      content={generatedBook} 
                      onAction={handleInteractiveAction}
                      bookTitle={book?.title}
                    />
                  </div>
                ) : (
                  <div className={styles.errorState}>
                    <p>Failed to load study guide.</p>
                    <button onClick={handleGenerateBook} className={styles.retryBtn}>Retry Generation</button>
                  </div>
                )}
              </div>
            </div>
          ) : viewUrl ? (
            (!viewUrl.toLowerCase().includes('.pdf') && !forceShowViewer && !generatedBook) ? (
              <div className={styles.externalResource}>
                <div className={styles.externalContent}>
                  <ExternalLink size={48} className={styles.externalIcon} />
                  <h2>External Resource</h2>
                  <p>This content cannot be embedded directly in the reader.</p>
                  
                  <div className={styles.externalActions}>
                    <a href={viewUrl} target="_blank" rel="noopener noreferrer" className={styles.openExternalBtn}>
                      Open Resource <ExternalLink size={16} />
                    </a>
                    <button 
                      onClick={() => setForceShowViewer(true)} 
                      className={styles.forceViewBtn}
                    >
                      Try to View in Reader
                    </button>
                  </div>

                  <div className={styles.aiGenerationSection}>
                    <div className={styles.divider}><span>OR</span></div>
                    <button 
                      onClick={handleGenerateBook}
                      disabled={isGeneratingBook}
                      className={styles.generateBookBtn}
                    >
                      {isGeneratingBook ? (
                        <>
                          <Loader2 size={18} className={styles.spin} />
                          Generating AI Study Guide...
                        </>
                      ) : (
                        <>
                          <Sparkles size={18} />
                          Generate AI Study Guide
                        </>
                      )}
                    </button>
                    <p className={styles.aiHint}>Create an instant AI-powered e-book summary for this resource.</p>
                  </div>
                </div>
              </div>
            ) : generatedBook ? (
              <div className={styles.generatedBookContainer}>
                <div className={styles.generatedBookHeader}>
                  <div className={styles.generatedTitleGroup}>
                    <Sparkles size={20} className={styles.aiIcon} />
                    <h2>AI Study Guide: {book.title}</h2>
                  </div>
                  <button onClick={() => setGeneratedBook(null)} className={styles.closeGeneratedBtn}>
                    Close Guide
                  </button>
                </div>
                <div className={styles.generatedBookContent}>
                  {isAiThinking && studyView !== 'content' ? (
                    <div className={styles.quizLoading}>
                      <Loader2 size={32} className="animate-spin text-emerald-500" />
                      <p>Generating your {studyView}...</p>
                    </div>
                  ) : renderStudyContent()}
                </div>
              </div>
            ) : useNativeViewer ? (
              <div className={styles.pdfWrapper}>
                <div className={styles.pdfControls}>
                  <div className={styles.pdfControlGroup}>
                    <button 
                      onClick={() => setPageNumber(prev => Math.max(prev - 1, 1))} 
                      disabled={pageNumber <= 1}
                      className={styles.pdfBtn}
                    >
                      <ChevronLeft size={20} />
                    </button>
                    <span className={styles.pageInfo}>
                      Page {pageNumber} of {numPages || '--'}
                    </span>
                    <button 
                      onClick={() => setPageNumber(prev => Math.min(prev + 1, numPages || prev))} 
                      disabled={pageNumber >= (numPages || 1)}
                      className={styles.pdfBtn}
                    >
                      <ChevronRight size={20} />
                    </button>
                  </div>
                  
                  <div className={styles.pdfControlGroup}>
                    <button onClick={() => setScale(prev => Math.max(prev - 0.1, 0.5))} className={styles.pdfBtn} title="Zoom Out">
                      <ZoomOut size={18} />
                    </button>
                    <input 
                      type="range" 
                      min="0.5" 
                      max="2.0" 
                      step="0.1" 
                      value={scale} 
                      onChange={(e) => setScale(parseFloat(e.target.value))}
                      className={styles.zoomSlider}
                      title={`Zoom: ${Math.round(scale * 100)}%`}
                    />
                    <button onClick={() => setScale(prev => Math.min(prev + 0.1, 2.0))} className={styles.pdfBtn} title="Zoom In">
                      <ZoomIn size={18} />
                    </button>
                    <span className={styles.scaleInfo}>{Math.round(scale * 100)}%</span>
                  </div>

                  <button 
                    onClick={() => setUseNativeViewer(false)} 
                    className={styles.fallbackBtn}
                    title="Switch to Google Viewer"
                  >
                    Switch Viewer
                  </button>
                </div>

                <div className={styles.pdfDocument}>
                  <Document
                    file={viewUrl}
                    onLoadSuccess={({ numPages }) => setNumPages(numPages)}
                    onLoadError={(error) => {
                      console.error('PDF Load Error:', error);
                      setUseNativeViewer(false);
                    }}
                    loading={
                      <div className={styles.pdfLoading}>
                        <Loader2 className={styles.spin} size={32} />
                        <p>Loading PDF...</p>
                      </div>
                    }
                    error={
                      <div className={styles.pdfError}>
                        <p>Failed to load PDF. Switching to fallback viewer...</p>
                      </div>
                    }
                  >
                    <Page 
                      pageNumber={pageNumber} 
                      scale={scale} 
                      renderTextLayer={true}
                      renderAnnotationLayer={true}
                      className={styles.pdfPage}
                      width={window.innerWidth > 1000 ? (showAiSidebar ? 600 : 800) : window.innerWidth - 48}
                    />
                  </Document>
                </div>
              </div>
            ) : (
              <>
                {/* Use Google Docs Viewer for documents, plain iframe for others */}
                <iframe 
                  src={
                    (viewUrl.toLowerCase().includes('.pdf') || 
                     viewUrl.toLowerCase().includes('.doc') || 
                     viewUrl.toLowerCase().includes('.ppt')) 
                      ? `https://docs.google.com/viewer?url=${encodeURIComponent(viewUrl)}&embedded=true`
                      : viewUrl
                  }
                  className={styles.pdfFrame}
                  title={book.title}
                />
                
                <div className={styles.fallbackBar}>
                   <p>Having trouble viewing this document?</p>
                   <div className={styles.fallbackActions}>
                     <a href={viewUrl} target="_blank" rel="noopener noreferrer" className={styles.fallbackBtn}>
                       Open in New Tab <ExternalLink size={14} />
                     </a>
                     <button 
                      onClick={() => setUseNativeViewer(true)} 
                      className={styles.retryBtn}
                     >
                       Try Native Viewer
                     </button>
                   </div>
                </div>
              </>
            )
          ) : (
            <div className={styles.noFile}>
              <p>No PDF file associated with this record.</p>
            </div>
          )}
        </div>

        {/* AI Sidebar */}
        {showAiSidebar && (
          <aside className={styles.aiSidebar}>
            <div className={styles.aiSidebarHeader}>
              <div className={styles.aiTitleGroup}>
                <Sparkles size={18} className={styles.aiIcon} />
                <h3>DARA AI Tutor</h3>
              </div>
              <div className={styles.aiHeaderActions}>
                <button onClick={clearChat} className={styles.headerActionBtn} title="Clear Chat">
                  <X size={16} />
                </button>
                <button onClick={() => setShowAiSidebar(false)} className={styles.closeAiBtn}>
                  <X size={20} />
                </button>
              </div>
            </div>

            <div className={styles.aiQuickActions}>
              <button 
                onClick={() => setIsStudyMode(!isStudyMode)}
                className={`${styles.quickActionBtn} ${isStudyMode ? styles.activeStudy : ''}`}
              >
                <BookOpen size={14} />
                {isStudyMode ? 'Exit Study Mode' : 'Start Study Session'}
              </button>
              {!isStudyMode && (
                <>
                  <button 
                    onClick={handleSummarize} 
                    disabled={isSummarizing || isAiThinking}
                    className={styles.quickActionBtn}
                  >
                    {isSummarizing ? <Loader2 size={14} className={styles.spin} /> : <BookOpen size={14} />}
                    Summarize Book
                  </button>
                  {QUICK_QUESTIONS.map((q, i) => (
                    <button 
                      key={i}
                      onClick={() => handleSendMessage(null, q)}
                      disabled={isAiThinking}
                      className={styles.quickActionBtn}
                    >
                      <MessageSquare size={14} />
                      {q}
                    </button>
                  ))}
                </>
              )}
            </div>

            {isStudyMode && (
              <div className={styles.studyModePanel}>
                <div className={styles.studyHeader}>
                  <Sparkles size={16} className={styles.aiIcon} />
                  <h4>Active Study Session</h4>
                </div>
                <div className={styles.studyToolsGrid}>
                  <button 
                    onClick={() => handleStudyAction('summary')}
                    className={`${styles.studyToolBtn} ${studyView === 'summary' ? styles.activeTool : ''}`}
                  >
                    <BookOpen size={14} />
                    Summary
                  </button>
                  <button 
                    onClick={() => handleStudyAction('flashcards')}
                    className={`${styles.studyToolBtn} ${studyView === 'flashcards' ? styles.activeTool : ''}`}
                  >
                    <Zap size={14} />
                    Flashcards
                  </button>
                  <button 
                    onClick={() => handleStudyAction('quiz')}
                    className={`${styles.studyToolBtn} ${studyView === 'quiz' ? styles.activeTool : ''}`}
                  >
                    <HelpCircle size={14} />
                    Quiz
                  </button>
                  <button 
                    onClick={() => handleStudyAction('simplify')}
                    className={`${styles.studyToolBtn} ${studyView === 'simplify' ? styles.activeTool : ''}`}
                  >
                    <Lightbulb size={14} />
                    Simplify
                  </button>
                </div>
              </div>
            )}

            {relatedBooks.length > 0 && !isStudyMode && (
              <div className={styles.relatedBooksSection}>
                <div className={styles.relatedHeader}>
                  <BookOpen size={14} className={styles.relatedIcon} />
                  <h4>Recommended for You</h4>
                </div>
                <div className={styles.relatedGrid}>
                  {relatedBooks.map(rb => (
                    <Link key={rb.id} to={`/book/${rb.id}`} className={styles.relatedCard}>
                      <img 
                        src={rb.cover_image_url || 'https://picsum.photos/seed/book/100/150'} 
                        alt={rb.title}
                        referrerPolicy="no-referrer"
                      />
                      <div className={styles.relatedInfo}>
                        <h5>{rb.title}</h5>
                        <p>{rb.author_names?.split(',')[0]}</p>
                      </div>
                    </Link>
                  ))}
                </div>
              </div>
            )}

            <div className={styles.chatContainer}>
              {aiMessages.map((msg, idx) => (
                <div key={idx} className={`${styles.message} ${styles[msg.role]}`}>
                  <div className={`${styles.messageBubble} ${msg.role === 'assistant' ? 'markdown-body' : ''}`}>
                    {msg.role === 'assistant' ? (
                      <InteractiveMarkdown 
                        content={msg.text} 
                        onAction={handleInteractiveAction}
                        bookTitle={book?.title}
                      />
                    ) : (
                      msg.text
                    )}
                  </div>
                </div>
              ))}
              {isAiThinking && (
                <div className={`${styles.message} ${styles.assistant}`}>
                  <div className={`${styles.messageBubble} ${styles.thinking}`}>
                    <Loader2 size={16} className={styles.spin} />
                    Thinking...
                  </div>
                </div>
              )}
              <div ref={chatEndRef} />
            </div>

            <form className={styles.chatInputArea} onSubmit={handleSendMessage}>
              <input 
                type="text" 
                placeholder="Ask a question about this book..." 
                value={inputMessage}
                onChange={(e) => setInputMessage(e.target.value)}
              />
              <button type="submit" disabled={!inputMessage.trim() || isAiThinking}>
                <Send size={18} />
              </button>
            </form>
          </aside>
        )}
      </div>
    </div>
  );
}
